### ISSUE TITLE
Using without item (like minimap mods)

### ISSUE THREAD

**Issue by osipxd** [Hunternif/AntiqueAtlas#101]
I've created fork to add some features, but I don't know it is possible or not.

I have some questions:
1. I need to add possibility to open map without atlas item, for example, when you press button "M". It is possible? And what classes I need to change?
2. ~~It is possible to show full rendered map of server?~~ (Not needed)

P.S. Sorry for my bad english, it's not my first language.

**Comment by Hunternif** [comment]
1. This feature is planned for the future. But it did exist in the past, in fact, the first version of the mod didn't have the item and acted exactly in this way. Try looking through past commits. Although they would be really old and incompatible with the latest versions of Minecraft, it could give you some idea of how to implement this.
2. Map tiles are created by scanning every (x,z) position in every given chunk, so canning an entire world will take a long time. There is an old branch called "generate-huge-map-hack" or something like that, which implements a quick-and-dirty scan of a large area.
PS Привет)

**Comment by osipxd** [comment]
Thanks for answers! 
About 2nd: may be there are way to render full map once on server and sync cache with clients?

**Comment by OsipXD** [comment]
Please check my pull request. I've not tested it with many players.
