### ISSUE TITLE
Crash 1.10.2 "payload may not be larger than 1048576 bytes"

### ISSUE THREAD

**Issue by doomguy4** [Hunternif/AntiqueAtlas#103]
I ma using antiqueatlas-1.9.4-4.3.0.jar
I tried to connect to my server and I got the following exception on the server side "payload may not be larger than 1048576 bytes"
I have an atlas in my characters inventory

Here is a link to the atlas www.humenet.net/Minecraft/aAtlas_0.dat
Here is a link to the level file www.humenet.net/Minecraft/crashlevel.dat
Here is a link to my curse modpack www.humenet.net/Minecraft/Humenet%202017-1.0.zip

I have saved a backup copy of the world folder on my server in case you need it

**Comment by osipxd** [comment]
It's similar to #97 and #98

**Comment by coolAlias** [comment]
And #48 ;)

**Comment by Kenkron** [comment]
>Here is a link to the atlas

You have **no idea** how much time you just saved me :+1:

**Comment by Kenkron** [comment]
You, my friend, have one helluva server.  I count 88,060 explored chunks in that file (80252 in the overworld, 4557 in the end, 2384 in the nether, and 867 in another dimension).

Its safe to say, if you hadn't given me this file, it would be very difficult for me to test the packet rework.

**Comment by Kenkron** [comment]
Just tested that file in the new algorithm.  It went from 1.1MB uncompressed, to 508kB. Compressed, it went from 297kB to 24kB.

More importantly, the new algorithm breaks it down into bite sized pieces for your friendly neighborhood networking protocol.

**Comment by doomguy4** [comment]
Glad I could help, this is my favorite map mod.

**Comment by hanakocz** [comment]
Hi, so I am now also on a list of people affected by this xD Sorry to ask, but do you have any ETAs where fix to this will be live? Until then I am probably out of bussiness at our 1.10.2 server xD

**Comment by CovertJaguar** [comment]
Had three different people have login issues because of this today. =P

**Comment by Kenkron** [comment]
I have a partial fix that I can push now, and then finish later I think.
Let me give it a shot.
