### ISSUE TITLE
no such field error: OCEAN

### ISSUE THREAD

**Issue by GeekBeam** [Hunternif/AntiqueAtlas#111]
unable to launch when other mods are included, I assume this is due to not building the jar correctly, but I thought it prudent to report. 

[here](http://puu.sh/uHecG/2ca651a916.txt/2ca651a916.txt) is the link to the file

**Comment by tyra314** [comment]
I'd bet you try to run a deobfuscated version of the mod in a non-dev environment.

**Comment by GeekBeam** [comment]
I actually ran each on their own.

**Comment by tyra314** [comment]
I just tried to reproduce your issue. Pulled the mods listed in your crash report as far as I could. Thrown in my personal build from latest git commit. Had no issues. There is something wrong with your build, not the code.

*edit: However, thanks for reporting anyways. Maybe you try to build it from scratch again.

**Comment by Hunternif** [comment]
@GeekBeam if you provided the `jar` file we could take a look at it.

**Comment by GeekBeam** [comment]
here's the jar I am working with: http://puu.sh/uJbI1/1adba1b4f3.jar

**Comment by tyra314** [comment]
See #112. I've checked your link, you're using a deobfuscated jar file. I don't know, what went wrong in your build, if you have used the wrong file, or where you got that file from, but it's a deobfuscated jar, which cannot be run outside of a development environment.
