### ISSUE TITLE
Some tweaks suggestion

### ISSUE THREAD

**Issue by Sirse** [Hunternif/AntiqueAtlas#114]
1. Configurable whitelist for worlds (AA are useless in some dimensions, eg thaumcraft/the end).
2. Automatic or manual (with command) cleaning of outdated AA files (eg: older than 3 months). On server i have about 1.5k of data files, but huge part of them are useless.
//(FileInfo) file.getLastModified() ?

Sorry me my English, i m russian, i hope you understand me)

**Comment by Kenkron** [comment]
Could you resubmit these as two separate issues. I'm sorry if it sounds pointless, but it makes it easier to keep track of what has been done, and what has not.
