### ISSUE TITLE
Junk data files cleaning

### ISSUE THREAD

**Issue by Sirse** [Hunternif/AntiqueAtlas#116]
Maybe implement automatic or manual (with command) cleaning of outdated AA files (eg: older than 3 months)? 
My server stores about 1.5k of data files, but huge part of them are useless.
//(FileInfo) file.getLastModified() ?

**Comment by Kenkron** [comment]
I'm not particularly inclined to delete old atlas data from within the game.  1.5k is a pretty small amount, in will go down now that the packet rework is live. If you want functionality like this, you could probably use a bash script like:

```bash
find ./world/data -mtime +90 -type f  -regex "aaMarkers_" -delete
find ./world/data -mtime +90 -type f -regex "aAtlas_" -delete
```

I haven't tested it, but you probably get the idea. The `-mtime +90` is what tells it to filter out files that are at least 90 days old, [I think](https://stackoverflow.com/questions/13489398/delete-files-older-than-10-days-using-shell-script-in-unix).
