### ISSUE TITLE
Full update to Java 1.8 (or removing 1.7 comatibility)

### ISSUE THREAD

**Issue by osipxd** [Hunternif/AntiqueAtlas#118]
I think it's ok to use Java 1.8 as target version. Because now percentage of Java 1.7 users is very small.
(here should have been a screenshot with statistics, but MCStats down again)

Any objections?

**Comment by Kenkron** [comment]
I didn't think there was anything in Antique Atlas that was incompatible with Java 1.8.   Is this just a matter of changing java target versions?

**Comment by osipxd** [comment]
And possibility to use features of Java 8, lambdas and streams for example

**Comment by Kenkron** [comment]
Sounds good, but we should probably close this as an issue. Its more of a coding practice than a solveable issue, and I saw you already switched a bunch of code to Java 8 style already.

**Comment by osipxd** [comment]
Ok
