### ISSUE TITLE
Atlas Combining

### ISSUE THREAD

**Issue by Kenkron** [Hunternif/AntiqueAtlas#127]
Atlases cannot be combined properly.

**Comment by Kenkron** [comment]
Fun fact, there is a commit from tyra314 that solves this: https://github.com/tyra314/AntiqueAtlas/commit/d0dfc6562b5ba42bfed80e2e8b3e845435b334d0

I feel like it was supposed to be merged. I'll just recreate the differences I guess.  There aren't very many

**Comment by osipxd** [comment]
I've merged this commit to 1.11.2 branch. Isn't?
Or you about 1.8 - 1.9 branches?

**Comment by Kenkron** [comment]
Huh, now that I look again, the changes are there.  I guess I just wasn't able to find the commit hash.

I was trying to fix this on the 1.9.4 branch, and was hoping to cherry pick that commit, but it didn't work.

**Comment by osipxd** [comment]
Also see this commit https://github.com/AntiqueAtlasTeam/AntiqueAtlas/commit/47e68efb96f7f103a7acc4a296602b9c2edb6950

**Comment by Kenkron** [comment]
Okay, this does seem to make the composite map stick around. Now i just need to make them combine their data correctly.
