### ISSUE TITLE
(Compat issue) [1.11.2] Atlas crash with Aether Legacy

### ISSUE THREAD

**Issue by Not-February** [Hunternif/AntiqueAtlas#129]
https://gist.github.com/Febilian/1441ea6a2f7abc57c535bf44d9cb93aa

Let me know if you need more details. Removing the atlas from the player with a NBT editor allows them to log back in, but basically I think as soon as the atlas starts to try to map the Aether, the player is unable to log into a world until the atlas is forcibly removed.

**Comment by Kenkron** [comment]
Note to self: port 4.4.9 to 1.11.2

**Comment by tyra314** [comment]
I think a4f1ea3b3363aeeaa977a43cd0361f256d7bda9c should fixes this in the 1.12 branch. If the problem persists please reopen this issue.

There probably won't be a backport to 1.11.
