### ISSUE TITLE
Crash when hovering over crafted atlas

### ISSUE THREAD

**Issue by Avarice** [Hunternif/AntiqueAtlas#143]
https://paste.ee/p/KrpDi

Tried it in a Tinker's Table first, then in character inventory. When hovered over in J/NEI, given the message "Tooltip Error."

**Comment by Kenkron** [comment]
Which build is this?

**Comment by TehNut** [comment]
`antiqueatlas-1.11.2-4.4.3.jar`

**Comment by Kenkron** [comment]
Do you have a crash log for this?

**Comment by tyra314** [comment]
The original link isn't available anymore.
