### ISSUE TITLE
Mystcraft and Atlas buggy interaction

### ISSUE THREAD

**Issue by Knightcoreframe** [Hunternif/AntiqueAtlas#151]
After checking with some Mystcraft people, it seems these crashes are linked to Antique Atlas.
[crash-2017-08-08_01.34.43-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1208434/crash-2017-08-08_01.34.43-server.txt)
[crash-2017-08-08_01.42.35-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1208437/crash-2017-08-08_01.42.35-server.txt)
[crash-2017-08-08_01.50.40-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1208436/crash-2017-08-08_01.50.40-server.txt)
[crash-2017-08-08_01.18.01-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1208439/crash-2017-08-08_01.18.01-server.txt)
[crash-2017-08-08_01.23.30-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1208435/crash-2017-08-08_01.23.30-server.txt)
[crash-2017-08-08_01.29.57-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1208438/crash-2017-08-08_01.29.57-server.txt)
Antique Atlas has been a great mod for me to map every dimension so I can get back home, even ones like Aroma1997's Mining Dimension, but it seems it has an issue with Mystcraft. I figured that it would be a good idea to post this here and hope that one day it could be taken care of. Could someone at least identify what the problem is specifically? All that I was told was that it was an Antique Atlas issue and not Mystcraft's, but it caused severe lag and crashes so hopefully the problem can be easily traced.

Thanks for all the help! I really appreciate any insight into this issue.

**Comment by Kenkron** [comment]
Thanks for the bug report!

Just glancing at the log, it looks like AA is probably crashing because it doesn't recognize the Mystcraft dimensions.

Mystcraft is one of my favorite mods, and I was really excited to see it updated to 1.11.2. I'll see if I can get this fixed by Friday.

Note to self: [commit that implemented biome registry]( https://github.com/AntiqueAtlasTeam/AntiqueAtlas/commit/574ceb537f771480590d566aac4c3c80a2af50ed)

**Comment by liach** [comment]
https://github.com/AntiqueAtlasTeam/AntiqueAtlas/commit/574ceb537f771480590d566aac4c3c80a2af50ed#diff-f9e118deb90adbfe2aae1da9f2e76a1fR103

**Comment by Kenkron** [comment]
I just tried AA with four mystcraft dimensions, and it worked. However, I think mystcraft can draw on biomes introduced by other mods, do you know if any of your mods add new or unusual biomes? Also, did this happen in *all* dimensions, or just *some* dimensions?

**Comment by tyra314** [comment]
As the patch was applied, I assume this is fixed, so I'm closing it now.

**Comment by tyra314** [comment]
For reference, the PR was this: #110
