### ISSUE TITLE
[1.12] Any atlas made after the first one has no terrain detail

### ISSUE THREAD

**Issue by Zachs-Kappler** [Hunternif/AntiqueAtlas#152]
I lost the first atlas I made and decided to make a new one, but it won't load in terrain details. This also goes for the overlay version in the upper right. Thankfully it still tracks me and I can add markers.

While writing this, I was trying different options to see if that might get it to draw the terrain details, and something happened while changing the itemneeded option that made it fill the atlas with terrain details. Still might be something to look in to.

**Comment by TehNut** [comment]
Hmm. I did not notice this during the port. Will take a look later today.

**Comment by jjc54** [comment]
Hmm so a short-term fix is just to change the item-needed option in the config?

**Comment by oitsjustjose** [comment]
Any update on this? It's still a problem and makes Antique Atlas useless beyond whoever makes one first..

**Comment by Kenkron** [comment]
Sorry, I've been busy since October.  We just seem to cram all of the
holidays into the last months of the year, then run around in a frenzy.

**Comment by Boymann** [comment]
Just to confirm another case, it's happening with us too. It basically makes the atlas only usable one player on the server (Unless the others are not bothered by logging in and out to refresh the atlas). Version 4.4.4

**Comment by CarmenCelen** [comment]
jup, happened to me too, all except my marker erased and not redrawing

**Comment by Kenkron** [comment]
Sorry for the wait. Fixed as of 724f9787840f3ba2acd3ceeb617ce98b07db09fb. Turns out there were just some commits that had been overlooked in the transition from 1.11 to 1.12
