### ISSUE TITLE
[1.12.2] Crash when loading the Game

### ISSUE THREAD

**Issue by MasterEnderman** [Hunternif/AntiqueAtlas#154]
Forge: 14.23.0.2540
Antique Atlas: 4.4.4
Crash Report: https://pastebin.com/4txawR5b

**Comment by tyra314** [comment]
You're using NotEnoughIDs, which increases the number of possible biome ids. But AntiqueAtlas assumes that there are maximum 256 biomes. Either disable this particular feature in NotEnoughIDs, if that is possible or try running the pack without that mod.
