### ISSUE TITLE
(MC 1.11.2) Crash when loading a certain biome 

### ISSUE THREAD

**Issue by Xogue** [Hunternif/AntiqueAtlas#155]
Not sure what biome it is, and it may not even be an error with the atlas and just an error with how the biome was registered with it. just curious if an exception catch can be made to prevent it from crashing the world when this happens. Perhaps just leave the biome empty on the map so no extra information is needed about the unknown biome?

Either way, removing atlas from the pack does remove the crash so it is tied to the mod in some way (even if it is the other mod's fault) Here is the crash log.

[crash-2017-11-18_12.17.39-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1484840/crash-2017-11-18_12.17.39-client.txt)

**Comment by tyra314** [comment]
I think a4f1ea3b3363aeeaa977a43cd0361f256d7bda9c should fix this for 1.12. If the problem persists in the next version, please reopen this issue.

Having said that, there will probably no backport to 1.11.
