### ISSUE TITLE
[1.12.2] Crash when entering the Aether (Legacy)

### ISSUE THREAD

**Issue by Shahelion** [Hunternif/AntiqueAtlas#158]
https://hastebin.com/litekopuwi.sql

**Comment by metoray** [comment]
The same error also occurs when entering a compact machine from the compact machines mod.

**Comment by cadaverous-eris** [comment]
The issue seems to be that the default system used to determine what tile should be drawn for a given location is meant only for use in the overworld, and crashes when it checks a location with no blocks at all down to the void.

**Comment by Kenkron** [comment]
I just released 4.4.9. See if that fixes it.
