### ISSUE TITLE
Unable to add custom markers

### ISSUE THREAD

**Issue by ghost** [Hunternif/AntiqueAtlas#162]
Adding a new entry to the list as so:

"antiqueatlas:bed": {},
 ...
    "antiqueatlas:village": {},
    "nocturneblock:textures\gui\markers\bedblue.png": {}

either gives one a pink/black error texture or this error: java.util.IllegalFormatConversionException: d != java.lang.String

**Comment by TehNut** [comment]
Should probably just be `nocturneblock:bedblue`?

**Comment by ghost** [comment]
@TehNut nope, crashes the game

**Comment by TehNut** [comment]
Full log?

**Comment by ghost** [comment]
@TehNut 

config file: https://pastebin.com/cxrpQ4E0

Crash report:
https://pastebin.com/5j0fNttc

Full log: 
https://gist.githubusercontent.com/Titus-Armillius/c7d44a54d436f6d60f0ced846f2a6907/raw/8e2eac52afc80075e8691e74c0e1b0df393af372/log

**Comment by TehNut** [comment]
Did you solve this?

**Comment by ghost** [comment]
@TehNut yes

**Comment by Targren** [comment]
@Titus-Armillius  Sorry for the necro, could you tell me how you solved it?
