### ISSUE TITLE
Totally useless with mods

### ISSUE THREAD

**Issue by Thyriel** [Hunternif/AntiqueAtlas#163]
Seems the atlas is rendering the world based on the seed number ignoring everything that other mods do change about world generation.
As sweet as the map looks like, that makes it totally useless unless you play vanilla with only atlas as mod.

Sky mods: Void dimension rendered as if it would be a vanilla world
Dimensions from mods (twilight forest, galacticraft etc.): Empty map
Mods that add/remove structures: Completely ignored by the map. You end up with villages / structures on the map that are not there and others missing.
Disable structures in world: Structures still appear on map

**Comment by GeminiMarshdevil** [comment]
this is accurate, tested with Lost Cities mod on every variation of the city render settings and OTG Biomes bundle.
http://prntscr.com/igbyiu


i'll give you the same offer i made the mod creator of animania, i have access to a data server rack and a team of testers which includes me among them, i'd like to use this mod in a new hardcore modpack im creating and so im willing to give you any and all support you need to fix this mod up proper. just give me a msg at my discord https://discord.gg/5FPK6v9

**Comment by Kenkron** [comment]
Now that I've gotten the 1.12.2 version out, this is the next bug on my
list. Justinrusso and tehnut have already done some work on this.

**Comment by TehNut** [comment]
Are Lost Cities considered biomes? If not, they'll need their own `IStructureWatcher`. Shouldn't be too hard to add. If they're biomes, https://github.com/AntiqueAtlasTeam/AntiqueAtlas/pull/161 *should* help with it.

**Comment by Kenkron** [comment]
That's a good point. It's almost certainly a biome issue to some degree.
Gemini reports a lot of ocean with small patches of mooshroom island on his
maps, and I think Lost Cities has a terrain gen overhaul, so it might just
need a texture pack. Oceans might be the default texture for the range of
values that lost cities uses uses for it's biomes, and if I were a modder,
mooshroom biomes would be the perfect way to prevent mobs from spawning in
a particular part of the map.

I'll try to get a deobf jar of Lost Cities and see if #161 really does help.

**Comment by esotericist** [comment]
> Are Lost Cities considered biomes? If not, they'll need their own IStructureWatcher. Shouldn't be too hard to add. If they're biomes, #161 should help with it.

They are definitely not biomes, and I don't think they're anything like vanilla structures. Lost Cities [has its own API](https://github.com/McJty/LostCities/tree/1.12/src/main/java/mcjty/lostcities/api) though.

**Comment by esotericist** [comment]
@Kenkron for what it's worth, i have a [fairly hacky Lost Cities compatibility mod here](https://github.com/esotericist/antiquecities/).

I didn't attempt to do it as a modification to antique atlas (and thus position for a pull request) because I have a great deal of trouble reasoning about java, and complex codebases are very difficult for me.

That said, it seems like this sort of thing seems like a good use of the API (barring the limitations I mention in #195 ), so unless you think it needs to be in Antique Atlas itself, I'll continue working on this (while lightly nudging McJty to improve his Lost Cities API as well, which is currently incomplete for these purposes).

**Comment by LaysDragon** [comment]
for sky island world, like sevtech sky island version modpack, it would be better to making a obvious boundary between void biome and normal biome.

**Comment by tyra314** [comment]
Mod compatibility can be achieved using resource packs since 6.0.0. So this generic issue is obsolete.
