### ISSUE TITLE
Atlas is not generating map

### ISSUE THREAD

**Issue by Dente222** [Hunternif/AntiqueAtlas#165]
As the name says my Atlas is not generating map
I'm playing on small modpack with my firend and his atlas works for me and him my one works for him only, I swap the atlas but its not generating more than the chunk of map that he generated :L
Here is the picture: https://i.imgur.com/b0d5Zhk.png

**Comment by Kenkron** [comment]
Which version is this?

**Comment by Dente222** [comment]
Latest for mc 1.12.2

**Comment by TehNut** [comment]
#152

**Comment by Dente222** [comment]
Sorry version 4.4.4 for 1.12.2

**Comment by Kenkron** [comment]
Fixed as of 724f9787840f3ba2acd3ceeb617ce98b07db09fb.
