### ISSUE TITLE
Crash when generating new chunks with BOP

### ISSUE THREAD

**Issue by ChiefLogan3010** [Hunternif/AntiqueAtlas#168]
After flying around the world for a while in creative, a crash will randomly occur when loading new chunks.
https://gist.github.com/ChiefLogan3010/e3efa6b3eff61b7808c1177abfd4a939

**Comment by Kenkron** [comment]
Actually, this looks like a village structure generation issue, so it might
not be about BOP. In fact, If memory serves, the Railcraft Patreon Server
has been using AA and BOP together for a while without issue (Admittedly,
that was on 1.10.2). Do you know which of your mods might be generating
structures in a village? I took a quick look at the mod list (looks fun,
btw), but didn't recognize any structure generators.

**Comment by ChiefLogan3010** [comment]
I've intentionally kept stucture generating mods to a minimum in order to make players unable to skip early game through loot. The only mod I can think of that messes with villages is Better With Mods, which has a hardcore feature which disables certain blocks in villages in a configurable radius from spawn in order for them to look looted. I have disabled the Immersive Engineering villager house in the config, so it hopefully shouldn't be that.

With regards to the pack, it's an in-dev hardcore pack that intends to make early-game a lot harder and more immersive.

**Comment by TehNut** [comment]
Did 1.12 change the format that Villages are stored in? The village data (which used to only provide positions, I guess) is providing a `DeletedStructures` tag, now, which is then blindly looped over and attempts to create a `WatcherPos` out of.

**Comment by Kenkron** [comment]
I'm trying to recreate this with Antique Atlas 1.12.2-4.4.6 and BiomesOPlenty 1.12.2 7.01.2330. I've come across some villages, but haven't gotten any crashes. About how frequently does this occur?

**Comment by ChiefLogan3010** [comment]
I doesn't happen with every village, so I'm not sure whether it's certain structures within villages or certain types of wood that villages are based on. It's also possible it's not anything to do with BOP but another mod that messes with villages. Regardless of the cause it seems random how often it occurs, sometimes upon world load and sometimes after 5 minutes of flying in creative.

**Comment by Kenkron** [comment]
I'll do some more exploring then.

**Comment by Kenkron** [comment]
Apparently fixed by #169.
