### ISSUE TITLE
Problem with AntiqueAtlas and WizardryMod 1.12.2

### ISSUE THREAD

**Issue by Burnhound** [Hunternif/AntiqueAtlas#170]
Whenever an active atlas is taken into the WizardryMod's alternate dimension, it crashes. 

"The game crashed whilst ticking player
Error: java.util.NoSuchElementException"

[crash-2018-03-02_21.20.23-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1777018/crash-2018-03-02_21.20.23-server.txt)

This is my first time using this site, reporting a bug and everything. If more info is needed let me know! Have a good day :D If there's no reasonable way to fix it, or its not worth fixing, that is no problem.

**Comment by Kenkron** [comment]
I'll try re-creating the bug tomorrow.

**Comment by tyra314** [comment]
I think a4f1ea3b3363aeeaa977a43cd0361f256d7bda9c should have fixed that. Please reopen if the problem persists in the next release.
