### ISSUE TITLE
Mod ID is shown as examplemod

### ISSUE THREAD

**Issue by Darkhax** [Hunternif/AntiqueAtlas#171]
The ID of the mod is shown as examplemod. This is because the included mcmod.info file is not accurately set to reflect the actual modid of the mod.

**Comment by Kenkron** [comment]
Was this on a build you made yourself?

gradle.properties was accidentally reset for 1.12. I fixed it for 1.12.2, but coincidentally, forgot to commit and push the file until yesterday (the day of your comment). I'll double check when I get home.

**Comment by Darkhax** [comment]
No, this is in the build on Curse.

**Comment by Kenkron** [comment]
Well shucks, I thought I fixed that.

**Comment by tyra314** [comment]
Should be fixed now
