### ISSUE TITLE
[1.7.10] How to delete Dimensions in AntiqueAtlas?

### ISSUE THREAD

**Issue by Pokihead** [Hunternif/AntiqueAtlas#172]
Hey I just tried out some Myscraft dimeonsions and I always had my atlas with me. Later i deleted all dimensions I didn't liked. The Problem is everytime I or someone else joins the server the atlas mod is sending all dimension tiles also from the deleted dimensions and the more tiles he is sending the bigger the lag is if someone joins.

So my questions is, is there a way to delete dimensions from the atlas mod and how?
Using antique-atlas 4.4.0 on MC 1.7.10
Greetings and I love this mod :D

**Comment by Hunternif** [comment]
Hi! Sorry for the super late reply.
Currently you can't delete a single dimension's data from an atlas. But as a workaround, you can delete all data from a single atlas item that you've taken to those dimensions. Delete the files `<world directory>/data/aAtlas_N.dat` and `<world directory>/data/aaMarkers_N.dat` where N is the atlas id that appears on screen in the game, i.e. `Antique Alas #N`.

**Comment by Hunternif** [comment]
Or if you know how to edit NBT, you can try editing that `aAtlas_N.dat` file and delete the dimension data from it. I'm not sure how that works, but I've heard there's a program for that, and the labels inside the file should have some descriptions as to what dimension is where.
