### ISSUE TITLE
Exported map only shows initial area. (fixed on restart)

### ISSUE THREAD

**Issue by Pyromstr** [Hunternif/AntiqueAtlas#173]
When exporting the atlas as a .PNG the area drawn only shows the area rendered when the atlas was first created.

![atlas](https://user-images.githubusercontent.com/25850399/37874161-8c890900-3021-11e8-82d1-f4b946e80c90.png)

As far as I can tell the empty space is about the same size as the rendered map in-game. After a restart of the game the issue is fixed however, I'm guessing the file is only updated on world load?

![atlas3](https://user-images.githubusercontent.com/25850399/37874178-2ae624c0-3022-11e8-97d8-8e1863b971f3.png)

I'm running the 1.10.2 version, sorry if it's been fixed in a later version, just thought I should mention it!

**Comment by Kenkron** [comment]
Interesting. I've seen this happen before. I'll check to see if the fix
didn't make it into the 1.10.2 version.

**Comment by esotericist** [comment]
This is still an issue in antique atlas 1.12.2-4.4.9. While testing the exports with #196 I'm having to quit to main menu and re-load worlds to get the export results to be current with any reliability.

Strangely, sometimes it will show partial fragments if you close then re-open the atlas and export again, but they don't always persist:

![atlas-2018-07-16_09 27 13](https://user-images.githubusercontent.com/1569754/42771113-fa7eb4de-88da-11e8-9c33-93c1a65e1fb4.png)

![atlas-2018-07-16_09 29 29](https://user-images.githubusercontent.com/1569754/42771120-ffa94f46-88da-11e8-835e-fe686043b935.png)

![atlas-2018-07-16_09 29 44](https://user-images.githubusercontent.com/1569754/42771122-016f9ab0-88db-11e8-9109-12a9b369dbda.png)

All three were taken in the same session. Then after quitting to main menu, loading again, and it came out correctly:
![atlas-2018-07-16_09 32 38](https://user-images.githubusercontent.com/1569754/42771189-3433dee8-88db-11e8-877f-805b6ca39acf.png)

Now, I'll freely admit to not being a java programmer, just someone who has recently been forced to do things in java, but seems like the exporter somehow has a cache of the map that isn't being properly refreshed before the export process?

**Comment by tyra314** [comment]
There won't be another 1.12 update, so I'm closing this. If it's also happening on newer version, please report again.
