### ISSUE TITLE
NoSuchElementException crashing at getBiomeID

### ISSUE THREAD

**Issue by oitsjustjose** [Hunternif/AntiqueAtlas#174]
## Versions:

MinecraftForge: 14.23.2.2654
Antique Atlas: 4.4.7
[Full Modlist](https://paste.ee/p/VgdKz)

## What happens:

[Here](https://paste.ee/p/5cicN) is the crash log. It's an issue with the world and BiomeID's, and looks related to #159.

**Comment by The-Fireplace** [comment]
I'm having the same issue. This one occurred when I entered a door from the Dimensional Doors mod.
[Crash Report](https://paste.ubuntu.com/p/6KYDtxQt9x/).

Antique Atlas 4.4.7
Forge 14.23.3.2655

EDIT: It appears that once #161 is complete, it could fix this.

**Comment by Kenkron** [comment]
This should be fixed in 4.4.9
