### ISSUE TITLE
Custom texture sets not showing.

### ISSUE THREAD

**Issue by irish-brigid** [Hunternif/AntiqueAtlas#176]
I created some custom texture sets for Highlands biomes. I followed the instructions on the wiki exactly. Thing is, I get Minecraft's blank texture instead of the new sets.
![2018-04-11_11 42 43](https://user-images.githubusercontent.com/34656214/38630892-b6b87308-3da7-11e8-9b9f-5f260c6cec53.png)

I don't know what I'm doing wrong. The resource pack is loaded. The file structure is this:

> HighlandCustomTiles.zip
> --assets
> ----HighlandCustomTiles
> ------textures
> --------cold
> --------desert
> --------forest
> --------grassland
> -------- mountains
> --------savanna

Here's a sample from texture_sets.json:
>    "CANYON": [
>      "HighlandCustomTiles:textures/mountains/canyon1.png",
>      "HighlandCustomTiles:textures/mountains/canyon2.png"
>    ],

**Comment by TehNut** [comment]
Namespace must be lowercase if you're on 1.11 or 1.12.

**Comment by irish-brigid** [comment]
I'm on 1.7.10.

**Comment by mostlyfabulous** [comment]
Have you tried using his example resource pack? (https://github.com/AntiqueAtlasTeam/AntiqueAtlas/wiki/Editing-Textures)

**Comment by irish-brigid** [comment]
That links to the tutorial page for editing the json file. I didn't used the sample pack mentioned there, but I followed the instructions exactly. Anyway, I *did* finally manage to make my new textures work by adding them directly to the jar file.


________________________________

**Comment by Hunternif** [comment]
@irish-brigid sorry for the trouble. Config loading is probably broken at the moment. Would you mind updating the tutorial page describing what you did to make it work?

**Comment by irish-brigid** [comment]
I'm not really sure how to do that. And all I did was add the pictures to the mod's jar file.

________________________________

**Comment by tyra314** [comment]
I think this is a) solved and b) obsolete. So I'm closing it.
