### ISSUE TITLE
Crash when entering compact machines dimension

### ISSUE THREAD

**Issue by Yandols** [Hunternif/AntiqueAtlas#179]
Had an antique atlas in the hotbar with overlay enabled and entered a compact machine, the game crashed. I'm giving a wild guess that since compact machine dimensions basically have nothing to render on a map anyways there is nothing for the map to record into memory. 

I suggest (allow) blacklisting the compact machines dimension from being recorded by Antique Atlas as it is useless in that dimension anyways.

**Versions:**
Antique Atlas: 4.4.7
Forge: 14.23.3.2655
Minecraft: 1.12.2

**Crashlog:** https://paste.ee/p/JpzFI

**Comment by Kenkron** [comment]
Okay, this should be fixed in 1.12.9

**Comment by Kenkron** [comment]
No further comment. I must assume it's fixed.
