### ISSUE TITLE
Antique Atlas and Biome Bundle 

### ISSUE THREAD

**Issue by DietmarKrause** [Hunternif/AntiqueAtlas#181]
It seems that the mod Antique Atlas inside the pack doesnt show the non-vanilla bioms of "biombundle" 
 (https://minecraft.curseforge.com/projects/biome-bundle) properly. I have high terracotta hills as a biome but cannot see that biome as high hills in the map (it shows flat land). I am using the pack Nature's beauty from welsknight.

**Comment by mostlyfabulous** [comment]
Antique Atlas doesn't support non-vanilla biome mods (Biomes o' Plenty sort of works however) right now and you would have to manually define textures and tile sets for each biome and it's kinda tricky to do add them in right now (as far as I know).

**Comment by Kenkron** [comment]
This is right. You can add textures for biomes if you know their ids, but they're not there initially.
