### ISSUE TITLE
4.4.8 still crashes with unknown biomes

### ISSUE THREAD

**Issue by jepo** [Hunternif/AntiqueAtlas#182]
Entering a dimensional doors with an antique atlas still crashes the game with a no/unknown biomeID.

Should fail gracefully. Logs attached.

IGNORE FIRST ONE: [crash-2018-05-06_23.02.47-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1978478/crash-2018-05-06_23.02.47-client.txt)
[crash-2018-05-06_23.50.00-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1978479/crash-2018-05-06_23.50.00-server.txt)
[2018-05-06-5.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/1978482/2018-05-06-5.log)

**Comment by TehNut** [comment]
First log is completely irrelevant. It's a Thaumcraft crash.

**Comment by jepo** [comment]
Oops might have posted the log from the crash before!
The other two should be correct.

**Comment by Kenkron** [comment]
That second crash report refers to a `NoSuchElementException` at line 103. In the source, that line does not refer to a collection, and the entire section is surrounded by a try block specifically catching `NoSuchElementException`. This, combined with the fact that the manifest wasn't updated leads me to one conclusion:

>The last update changed literally nothing but the version number.

I usually pull down a local request on my machine, test merging it at home, then merge on github after confirming it worked on my computer. Then I pull the changes from github, except this time, I must have forgotten that part.

**Comment by Kenkron** [comment]
Try 4.4.9.
