### ISSUE TITLE
Duplicate mod id, examplemod

### ISSUE THREAD

**Issue by darkphan** [Hunternif/AntiqueAtlas#184]
Seems this mod is using a default Mod Id "examplemod" which is conflicting with another mod (animus, going to report this there as well).

[Screenshot](https://i.imgur.com/mRmCcZm.png)

**Comment by TehNut** [comment]
@Kenkron You seem to have copied the default classes from the MDK when you updated your environment to 1.12.2.

![image](https://user-images.githubusercontent.com/5789439/40086959-66331dca-5855-11e8-9759-9a1e17431cbc.png)

@darkphan Open the jar and delete the `com` directory from it.

**Comment by darkphan** [comment]
Thanks @TehNut

**Comment by Kenkron** [comment]
dang, fixing this was half the reason I uploaded 4.4.8.  I'll double check
next time.

**Comment by TehNut** [comment]
@Kenkron Make sure you run `gradlew clean` before building next time or you may end up with those classes again.

**Comment by Kenkron** [comment]
Thanks. Maybe that's where I went wrong.

**Comment by Kenkron** [comment]
I found out that I literally had the example mod that gradle auto-generates in my workspace. I just released 4.4.9, which should fix this.
