### ISSUE TITLE
[Wiki] Example Resource Pack texture download link broken

### ISSUE THREAD

**Issue by TheAtomicOption** [Hunternif/AntiqueAtlas#185]
The link to the example resource pack on the page below returns 404 not  #found:
https://github.com/AntiqueAtlasTeam/AntiqueAtlas/wiki/editing-Textures

**Comment by Kenkron** [comment]
Thanks for pointing that out.

**Comment by Hunternif** [comment]
Fixed now. Thanks again for pointing it out!
