### ISSUE TITLE
[1.12.2] Could not add new marker. Atlas is at it's limit of 1024 markers.

### ISSUE THREAD

**Issue by Alaberti** [Hunternif/AntiqueAtlas#187]
Seeing this on player join to a dedicated server. 

[main/WARN] [antiqueatlas]: Could not add new marker. Atlas is at it's limit of 1024 markers

**Comment by Kenkron** [comment]
This doesn't fully explain your issue, but I can tell you why there is a marker limit, and you can make it as high as you want in your config.

The marker limit is there to prevent some malicious person from filling your server with markers. If an atlas was allowed to have an infinite number of markers, Dr. Evil could make a script that just keeps adding them until your server runs out of ram.

Like I said, you can set this as high as you'd like.  The **real** question here is "Why does a player logging in try to add a new marker?"

**Comment by Alaberti** [comment]
I'll see if I can pull a log or something for you. This has been happening on version 1.12.2-4.4.9 whenever any player loads, regardless if they have an Atlas or not. Sorry for not having a lot of description initially.

**Comment by Alaberti** [comment]
After updating configs, no longer seeing this issue.
