### ISSUE TITLE
examplemod included in version 4.4.9 on CurseForge

### ISSUE THREAD

**Issue by DaemonUmbra** [Hunternif/AntiqueAtlas#191]
The 4.4.9 release here on GitHub seems to have had that derp fixed, however the CurseForge version seems to still have it

**Comment by DaemonUmbra** [comment]
![image](https://user-images.githubusercontent.com/5004171/40954306-f910fca0-6851-11e8-882e-173b32a295b4.png)

**Comment by tyra314** [comment]
Duplicate of #171
