### ISSUE TITLE
[Suggestion] Adding custom markers?

### ISSUE THREAD

**Issue by frenchiveruti** [Hunternif/AntiqueAtlas#193]
Is there a way to add my own png images to set markers? I think the actual ones are or pretty redundant or lacking.

**Comment by Kenkron** [comment]
Good news, it's an existing feature! https://github.com/AntiqueAtlasTeam/AntiqueAtlas/wiki/Adding-Custom-Markers

**Comment by frenchiveruti** [comment]
Ah, sorry then, well, for the future people on the internet then!

**Comment by esotericist** [comment]
@Kenkron Is that documentation correct?

I'm attempting to follow the instructions linked there, and I'm having a great deal of difficulty.

First off, the wiki claims the file is `marker_textures.json` but as far as I can tell the closest file is `markers.json`. If there's supposed to be a separate `marker_textures.json` it is failing to exist.

Following the example given inside the `markers.json` content, I cannot seem to figure out how to successfully add a custom marker. Everything I do either gets me a missing texture or causes antique atlas to delete the entry on startup.

Has this feature been verified to work recently? If it is known to work, can we get an example of how to correctly add a custom feature in the wiki?
