### ISSUE TITLE
Use of the Nomatic Tents mod results in nether portal markers everywhere.

### ISSUE THREAD

**Issue by Datsjive** [Hunternif/AntiqueAtlas#194]
So I've been playing the Homestead modpack on ATLauncher, and have been using the Nomadic Tents mod for mobile bases.

Since the inside of the tent is in a separate dimension, AA places a marker on the map due to it thinking I went through a Nether Portal. (This is my best assumption as to why.)

I went through the config files, but couldn't find an option to disable the automatic placement of Nether Portal markers. Is this an upcoming thing, or has no one mentioned this before?

**Comment by brisingraerowing** [comment]
I'd like this feature as well, as the automatic nether portal marker placement occurs with some other mods in my pack.

**Comment by Kenkron** [comment]
I should add a config option to disable this.
