### ISSUE TITLE
[1.12.2] Example Mod, Antique Atlas, Antique Atlas Overlay Crashes

### ISSUE THREAD

**Issue by PulseBeat02** [Hunternif/AntiqueAtlas#198]
When I try loading my modpack, it ends up with a crash saying that  Example Mod, Antique Atlas, Antique Atlas Overlay is the problem. Can you please find the answer why it is crashing?

Crash Report at: https://paste.dimdev.org/dokumezico.mccrash

**Comment by Kenkron** [comment]
There are an unusually high number of biome ids in your mod pack, and
AntiqueAtlas isn't handling them well. They probably came with
JustEnoughIds. Thanks for the crash report, I'll see what I can do.

**Comment by PulseBeat02** [comment]
True. I have a lot biomes in my modpack, so I used JustEnoughID's to get rid of the limit. When I read the crash report, it seems that the arrays you use have been exceeded, giving the error: 
java.lang.ArrayIndexOutOfBoundsException: 267

I'd suggest to extend your arrays so there can be more biomes.

**Comment by tyra314** [comment]
This should be fixed in a4f1ea3b3363aeeaa977a43cd0361f256d7bda9c, which is part of the new release. If the problem persists, please reopen the issue.
