### ISSUE TITLE
[1.7.10] What do I even do about this?

### ISSUE THREAD

**Issue by Shahelion** [Hunternif/AntiqueAtlas#199]
https://pastebin.com/bpKYHxm2

**Comment by PulseBeat02** [comment]
This is not Antique Atlas's fault, it is just that you have too many biome ID's forcing other biomes to have a negative ID. Use the mod "JustEnoughIDs" to fix this problem. JustEnoughIDs makes it so you can have as many biomes as you want.

**Comment by Shahelion** [comment]
But every biome ID is allocated within the limit. There shouldn't be any left over.

EDIT: As per the title, this is in 1.7.10. I wasn't posting expecting a fix from the mod or anything, just information if there was anything I could do.
