### ISSUE TITLE
Duplicate nether portal auto markers

### ISSUE THREAD

**Issue by tyra314** [Hunternif/AntiqueAtlas#209]
The check if a marker for a portal was already created only looks into the current chunk of the player. If a nether portal goes over chunk boundaries, one marker gets created in each occupied chunk.

**Comment by Hunternif** [comment]
This would be nice to fix, but it should be rare.

**Comment by tyra314** [comment]
Actually, it may not be as rare as one could think. Consider the standard 2 wide nether portal (for wider portals it's even worse):

There are 256 = 16x16 blocks in a chunk. And 64=16x4 blocks right next to a chunk border (I'm counting ~~edges~~ corners twice because they have two chunk borders. This means you already have a 1 in 4 chance to place a block right next to a chunk border when you randomly place a block in the world. For each of the border blocks, 1 of 4 directions will place the nether portal across a chunk border. Thus, you have a 1 in 16 chance to hit this issue, when you place a nether portal randomly in the world. That's not what I'd call rare :)

**Comment by Hunternif** [comment]
Markers are stored in "marker chunks" that are 8 times bigger than regular chunks.
Btw have you actually encountered this issue, or did you discover it by reading the code?

**Comment by tyra314** [comment]
There won't be another 1.12 update, so I'm closing this.

Also, those markers don't work at all in recent version...
