### ISSUE TITLE
[Technical] Automatic crash reports

### ISSUE THREAD

**Issue by osipxd** [Hunternif/AntiqueAtlas#211]
I working on [Inspector](https://gitlab.com/endlesscodegroup/inspector). It is the tool to automatically report about exceptions to author (to Discord or Sentry). Now there are implementation only for Bukkit, but core logic is independent and I can create also implementation for Forge.

Are we interested in it?

**Comment by Hunternif** [comment]
Wow this is cool. But plz don't let it spam discord 😥

**Comment by osipxd** [comment]
Sure. [Sentry](https://sentry.io/) is much better, and it is supported now by Inspector.
Ok, I'll try to add Forge support.

**Comment by tyra314** [comment]
While I think this is a good idea in general. I don't think it will add much. Crashes get reported quite reliably here on github. And frankly, I have no idea how to set this up.
