### ISSUE TITLE
“Adding custom markers” - question about instruction

### ISSUE THREAD

**Issue by mrJyggalag** [Hunternif/AntiqueAtlas#212]
So, I have simple question: will the resource pack with custom markers be added as an example in [
https://github.com/AntiqueAtlasTeam/AntiqueAtlas/wiki/Adding-Custom-Markers](url)? Because if i fllowing the wiki instructions, I cannot seem to figure out how to add a custom marker. If I just add a `antiqueatlas:ship_01` (“ship_01” - name of new marker, for example) in `markers.json` gets me a missing texture or if I add `antiqueatlasnewmarker:textures\marker\ship_01.png` causes antique atlas to delete the entry in `markers.json`

**Comment by tyra314** [comment]
Have you added a texture accessible by a resource location? For example using Resource Loader?

**Comment by Dever293** [comment]
How would you specify the location of a texture? Each time I try using Resource Loader I get a crash. Is there a possible example to follow?

**Comment by DaleHat** [comment]
So i've been trying to add just 1 icon its a 32x32 png i am using Resource Loader i dont have any crashes but AntiqueAtlas keeps removing my edits.. i started keeping backups of different ways i've tried editing the markers.json so i dont make the same mistake tho i do keep making a mistake somewhere which is why i assume AntiqueAtlas removes my changes below are different 'formats' ive tried.. the top being the latest

-----------------------------
    "antiqueatlas:village": {},
    "example:example": {example:textures/gui/markers/example.png, 1, -1000, 1000, false, true, true, 0.5, 0.5}
-----------------------------
    "antiqueatlas:village": {},
    "example:example": {example:textures/gui/markers/example.png,1,-1000,1000,false,true,true,0.5,0.5}
-----------------------------
    "antiqueatlas:village": {},
    "example:example": {"textures": example:textures/gui/markers/example.png,"size": 1,"clipMin": -1000,"clipMax": 1000,"alwaysShow": false,"isTile": true,"isTechnical": true,"centerX": 0.5,"centerY": 0.5}
-----------------------------

so with that maybe someone would be as so kind to point out the error in my ways perhaps even providing a example of the markers.json with a added entry..

**Comment by DaleHat** [comment]
well good news is i figured out how to stop it from removing my edits (i made the .json read-only)
bad news is it still doesnt show my marker as a option when creating a new marker on the map.. 

I also changed "isTechnical": true to false as i thought it needed to be true to be able to be a option on the map.. still nothin so i went and tried this

-----------------------
    "example:example": {"textures": `example:textures/gui/markers/example.png`}
-----------------------
and that didnt work so next would be to remove the .png at the end and that also didnt work..

**Comment by Kirin92** [comment]
Did it work in the end? I really want to add custom markers.

**Comment by AustinMajeski** [comment]
I figured it out.

Everyone (including myself) was typing their JSON in an invalid way.

\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\

	1.	Move this resourcepack into your "resourcepacks" folder.
	2.	< any order >
		a.	Open Minecraft and select to use this resourcepack.
		b.	Copy the contents of the file "markers.json.example.txt", 
			located inside this resourcepack, into the file "markers.json"
			 located inside your minecraft directory at
			"...\.minecraft\config\antiqueatlas".
	3.	Close Minecraft.
	4.	Open Minecraft.

Note:    The resourcepack must be selected for use when Minecraft is launched so the textures/icons can be loaded.
		
\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\


Sample image:  https://imgur.com/gallery/6kobT1z
Download:  https://www.mediafire.com/file/2txc35fwbix0yei/Antique_Atlas_Custom_Icons_Example_-_%25281.12.2%2529.zip/file

> PS:  This is a duplicate comment from another issue.  I think it would be easier found in the other issue-post at https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/283

**Comment by tyra314** [comment]
I guess this was answered a long time ago.
