### ISSUE TITLE
OS pop-up during world load with newest java

### ISSUE THREAD

**Issue by hfab** [Hunternif/AntiqueAtlas#213]
When I create or open a singleplayer world, a pop-up appears asking me to insert a disk into my DVD drive. Apparently the mod tries to open a file on the D: disk. I found this while starting FloraMancer and traced the problem to Antique Atlas. With all mods enable except Antique Atlas, the pop-up does not show up. With only Antique Atlas enabled the pop-up shows up. Updating to the latest version (from 4.4.9 to 4.5.0) does not fix it.
The issue has something to do with newer Java versions. It does occur with Jave 1.8.0_201, but not with 1.8.0_51.
Original issue at the Floramancer github: https://github.com/lucidobservor/floramancer-modpack/issues/6

**Comment by Kenkron** [comment]
This is the weirdest bug I've seen so far. I'm afraid the link doesn't lead anywhere. Can you attach a picture of the pop-up?

Also, what other mods are you using? Maybe there's a bad interaction.

**Comment by Kenkron** [comment]
Also, the link is broken.

**Comment by hfab** [comment]
I fixed the link in the original post. The pop-up I am getting is this:
![image](https://user-images.githubusercontent.com/31726022/51766359-a550b500-20da-11e9-843d-5c47f6ce3f76.png)
It happens with just Forge and Antique Atlas.
Here is a log of the issue in a newly created modpack with just Antique Atlas: https://paste.ee/p/RwfAD The pop-up is shown after the line "[antiqueatlas]: Saving local markers data to NBT" is printed.
Relevant versions:
OS: Windows 10 Home 1803 64 bit
Forge: 14.23.5.2768 (latest recommended version)
Minecraft: 1.12.2
Java: 1.8.0.201 64 bit
Antique Atlas: 4.5.0
Launcher: Multimc 0.6.5-develop-1295
I have tried the twitch launcher. That does not show the error with their default java (1.8.0.51), but does when the java version is updated to 1.8.0.201.

**Comment by Hunternif** [comment]
Hi hfab.
Could you please try this build and see if the issue appears again. (Rename it to .jar): [antiqueatlas-1.12.2-4.5.2.zip](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/3694689/antiqueatlas-1.12.2-4.5.2.zip)

**Comment by hfab** [comment]
Hello Hunternif,

Sorry for the delay in reacting to your comment. 
I cannot reproduce the issue anymore with this new version. But I also cannot reproduce it with the 4.5.0 version anymore. Java has updated to 1.8.0.221 since I encountered the issue and this update has probably changed something that solves the issue.
I see Oracle release a new Java update today (1.8.0.231) and this version also works correctly.
 So it was  probably a bug in the Java JRE.
Thanks for looking into it anyway,
