### ISSUE TITLE
Can not press onscreen buttons

### ISSUE THREAD

**Issue by agentwolf88** [Hunternif/AntiqueAtlas#218]
When i press the onscreen buttons there will not happens.

MC 1.12.2
latest Version of AA

**Comment by tyra314** [comment]
Can you elaborate more on the issue, please? Which buttons?

**Comment by Hunternif** [comment]
Please check if this happens with the latest version (v4.6.3)
Are you running any other mods?

**Comment by tyra314** [comment]
There won't be another 1.12 update, so I'm closing this.
