### ISSUE TITLE
Upgraded, now map changes to old incorrect version.

### ISSUE THREAD

**Issue by calloatti** [Hunternif/AntiqueAtlas#219]
MC 1.14
fabric-api-0.3.0-pre+build.156.jar

I upgraded  from antiqueatlas-5.0.0-alpha.1+fabric-unofficial.jar to antiqueatlas-5.0.0-fabric.jar

I noticed that antiqueatlas-5.0.0-alpha.1+fabric-unofficial.jar failed to map shallow water in some cases.

antiqueatlas-5.0.0-fabric.jar seems to correctly map these shallow water areas. Now, if I open the map book after loading the game, the map is correctly drawn:

![2019-05-17_19 37 01](https://user-images.githubusercontent.com/12817862/57959883-4d81c800-78dc-11e9-8846-aa3522cd8e76.png)

Notice the lake to the left of the marker/player position.

If I close the book, face west, and open the book again, the map reverts to the old wrong version:

![2019-05-17_19 37 14](https://user-images.githubusercontent.com/12817862/57959919-7609c200-78dc-11e9-9aee-3c5774eeecc4.png)

Closing the book and facing North again does not correct the problem:

![2019-05-17_19 37 22](https://user-images.githubusercontent.com/12817862/57959932-84f07480-78dc-11e9-86f5-0106cd26d0e6.png)

Is there a way to delete the map data without losing the markers? I don´t mind exploring the world again, I just want an accurate map with the missing lakes and river parts.

If you can also explain why this happens that would be nice too.

**Comment by tyra314** [comment]
This should be fixed in the 5.0.1 release. Please reopen if the issue still persists
