### ISSUE TITLE
Placing an antiqueatlas on the left hand slot crashes the game.

### ISSUE THREAD

**Issue by calloatti** [Hunternif/AntiqueAtlas#221]
Full multimc log: https://paste.ee/p/OMAd3

Saved game keeps crashing when trying to load it now.

**Comment by TehNut** [comment]
This line should be casting `stack2` rather than `stack`

https://github.com/AntiqueAtlasTeam/AntiqueAtlas/blob/5da646f7f9d8f91f9a2cf0e00a2bbe3025584126/src/main/java/kenkron/antiqueatlasoverlay/OverlayRenderer.java#L83

**Comment by tyra314** [comment]
Fixed in 5.0.3. Thanks for the patch.
