### ISSUE TITLE
Cloning an atlas recipe does not work in 1.14

### ISSUE THREAD

**Issue by calloatti** [Hunternif/AntiqueAtlas#223]
antiqueatlas-5.0.3-fabric

This may be in the todo list but bringing it up just in case. This does not work:

![image](https://user-images.githubusercontent.com/12817862/58161199-32091b00-7c56-11e9-9846-73a95b5edc40.png)

**Comment by tyra314** [comment]
Cloning fixed in 940f57ca28a01318ffb57cb1743f8c40ffbe78bb

Combining still doesn't work though.
