### ISSUE TITLE
Cannot create map markers.

### ISSUE THREAD

**Issue by WillTereika** [Hunternif/AntiqueAtlas#228]
Using the 1.14 Fabric version of the mod.  Tried to create a map marker, and it just refuses to place it at all.  Keep clicking to place it; it asks me to name it... infinite loop of his behavior and it NEVER places the marker.

**Comment by tyra314** [comment]
I just tested it, it seems to work for me. Can you please provide more details. What is the exact version you're using? Does it happen for you with only AA loaded? Singleplayer or server? Please also give a step-by-step what you're clicking, what happens and what would you expect to happen at each step?

**Comment by calloatti** [comment]
I have had problems creating markers in the nether. They just don't get created, until you restart the game.

**Comment by AshleighTheCutie** [comment]
I'm having this same issue in all dimensions, on 1.14.4. I can upload video proof if you want.

**Comment by CptRom** [comment]
As far as I can tell, you can't place a marker when the atlas is in your off hand but you can when it is not.

**Comment by tyra314** [comment]
I fixed that markers could not be created when the atlas was in the off-hand. If there are still other occurrences, when markers cannot be created, please reopen this issue.
