### ISSUE TITLE
Cannot connect to "vanilla"/bukkit server (invalid payload REGISTER)

### ISSUE THREAD

**Issue by zedwick** [Hunternif/AntiqueAtlas#232]
When connecting to a "vanilla"/bukkit server, the client is disconnected with "invalid payload REGISTER" message. Server side, the following is seen:

`org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 32 chars (attempted 38 - 'antiqueatlas:delete_custom_global_tile`

Running version 5.0.5-fabric.

**Comment by tyra314** [comment]
Both the server and client need the mod installed. And there is no bukkit version.

**Comment by zedwick** [comment]
Indeed. The mod should not function on bukkit, but should not break connecting to a server without it installed either.
