### ISSUE TITLE
Loading new texture pack causes crash

### ISSUE THREAD

**Issue by NomSTeh** [Hunternif/AntiqueAtlas#233]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/07/19 5:28 AM
Description: Rendering overlay

java.lang.RuntimeException: Attempted to register ID antiqueatlas:skull at different raw IDs (0, 15)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.class_2370.handler$setPre$zii000(class_2370.java:630)
	at net.minecraft.class_2370.method_10273(class_2370.java)
	at net.minecraft.class_2348.method_10273(class_2348.java:24)
	at net.minecraft.class_2370.method_10272(class_2370.java:50)
	at hunternif.mc.atlas.registry.MarkerRegistry.register(MarkerRegistry.java:22)
	at hunternif.mc.atlas.marker.MarkerTextureConfig.lambda$apply$2(MarkerTextureConfig.java:80)
	at hunternif.mc.atlas.marker.MarkerTextureConfig$$Lambda$2489/386176120.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.class_2370.handler$setPre$zii000(class_2370.java:630)
	at net.minecraft.class_2370.method_10273(class_2370.java)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.class_425
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:891)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:411)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- Affected level --
Details:
	All players: 1 total; [class_746['NomSTee'/12, l='MpServer', x=34.87, y=70.42, z=5249.96]]
	Chunk stats: Client Chunk Cache: 1089, 783
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-256,72,-84), Chunk: (at 0,4,12 in -16,-6; contains blocks -256,0,-96 to -241,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 986153 game time, 76312 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3837653000 bytes (3659 MB) / 6979321856 bytes (6656 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms512m
	Fabric Mods: 
		alwaysdroploot: Always Drop Loot 3.5.0+mc1.14.1
		amethystmod: Amethyst Mod 1.1.0
		antiqueatlas: Antique Atlas 5.0.6-fabric
		anvil_fix: AnvilFix 1.1.2
		appleskin: AppleSkin 1.0.6
		aquarius: Aquarius 1.3.1+1.14.1
		autoconfig1: Auto Config v1 1.1.2+mc1.14.1
		battle-towers: Battle Towers 1.0.3
		beaconflight: BeaconFlight 1.1.0
		betterthanmending: BetterThanMending 1.0.0
		betterutilities: Better Utilities 1.4.2
		biom4st3rpokeballs: Biom4st3rPokeballs 1.2.1
		block_booster: Block Booster 0.0.1
		blockmeter: Block Meter 1.1.2
		blockus: Blockus 1.1.12
		blue_endless_jankson: jankson 1.1.2
		chunkactivator: Chunk Activator 1.1.1+mc1.14.2
		cleardespawn: Clear Despawn 1.0.4
		cloth: Cloth Events 0.3.1+build.23
		cloth-config: Cloth Config 0.2.4+build.17
		cloth-config2: Cloth Config v2 0.2.0
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_json: json 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		composableautomation: Composable Automation 0.5.0+mc1.14.2
		cotton: Cotton 0.8.3-pre+1.14.3
		couplings: Couplings 1.0.0
		craftingpad: Crafting Pad 1.0.3
		crochet: Crochet 1.0.2
		cursedchests: CursedChests 2.3.22
		demesne: Demesne 1.14.3-2.2.7-FABRIC
		ding: Ding 2.0.3
		disenchanting: Disenchanting 0.8.1
		easyexcavate: Easy Excavate 1.5.1
		extradiscs: ExtraDiscs 1.0.3+build.5
		extrapieces: Extra Pieces 1.3.0
		fabric: Fabric API 0.3.0+build.187
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b75
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463
		fabric-furnaces: Fabric Furnaces 1.1.6
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+f0d56800
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c
		fabric-language-kotlin: Fabric Language Kotlin 1.3.30+build.2
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa6
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+bdffbb2c
		fabric-models-v0: fabric-models-v0 0.1.0+59147463
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+39ff57de
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+f0d56800
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.7+029ec62e
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35
		fabricloader: Fabric Loader 0.4.8+build.155
		faeriefire: Faerie Fire 1.0.1
		fastflyblockbreaking: Fast Fly Block Breaking 1.1.0
		fermion: Fermion 0.6.3+build.37
		fishtraps: Fish Traps 1.14.3-1.0.3
		flesh-2-leather: Flesh 2 Leather 0.1.4
		fluid-interactions: Fluid Interactions 1.1.0
		fmagnet: Fabric Magnet ${version}
		frex: FREX 0.7.3+build.71
		healthoverlay: Health Overlay 1.2.8
		iamverysmart: I Am Very Smart 1.4.0+mc1.14.1
		inca: Inca 1.0.4
		informedload: Informed Load 2.1.0-1.14
		inventory_hud: Inventory HUD 1.1.1
		inventorysorter: Inventory Sorter 1.2.1
		itemtooltips: ItemTooltips 1.0.1
		json-model-extensions: JSON Model Extensions 0.2.3+build.45
		leadvillagers: Lead Villagers 1.1.0+mc1.14.1
		leathercows: Leather Cows 1.0.0
		lettuce: Lettuce Not Crash 1.0
		leveluphp: Level Up HP 4.3.0+mc1.14.2
		libblockattributes_core: LibBlockAttributes (Core) 0.4.7
		libblockattributes_items: LibBlockAttributes (Items) 0.4.7
		libcd: LibCapableData 1.2.1+1.14.3
		lightoverlay: Light Overlay 1.2.1
		locatebiome: LocateBiome 1.0.1
		malilib: MaLiLib 0.9.6
		mbackpacks: Mpcs' Backpacks 1.1.4
		mendtrend: Mend Trend 1.0.2
		ml: More Layers 2.2.0
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.6.2-92
		moenchantments: Mo'Enchantments 1.5.8
		mycommands: MyCommands Fabric 1.14.2-06
		nbttooltip: NBT Tooltip 1.14-1.0.3
		net_fabricmc_stitch: stitch 0.2.1.61
		nightconfig4fabric: Night Config 4 Fabric 3.6.0
		optifabric: Optifabric 0.3.2
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		oysters: Oysters fabric-1.14.3-0.0.3
		permafrost: Permafrost 1.2.1
		playerplates: Player Plates 1.0.0
		polyester: Polyester 0.3.1+1.14.3
		prorenewal: Protection Renewal 1.0.0
		quick_crops: Quick Crops 1.1.1
		realinfinity: Real Infinity 1.0.3
		redstonebits: Redstone Bits 1.0.4+mc1.14.1
		redstonetweaks: Redstone Tweaks 1.0.2
		rgbblocks: Rgb Blocks 2.0.6
		roughlyenoughitems: Roughly Enough Items 2.9.6+build.138
		roughlyenoughresources: Roughly Enough Resources 1.1.0
		silkyspawners: Silky Spawners 1.0.2
		simpleteleporters: Simple Teleporters 2.1.0
		simplezoom: Simple Zoom 1.0.0
		smartermending: Smarter Mending 1.0.1
		soulbound: Soulbound 1.0.1
		soulsegg: Souls Egg 1.0.0
		stockpile: Stockpile 1.0.8+1.14.3
		target-dummy: Target Dummy 1.0.1
		tbo: TheBiomeOverhaul 1.2.0
		towelette: Towelette 1.7.2
		tramplestopper: Trample Stopper 1.0.0.27-universal
		trapexpansion: Trap Expansion 1.1.0
		tweakeroo: Tweakeroo 0.9.6
		vanilla-hammers: Vanilla Hammers 1.4.2
		vanilla-toolsets: Vanilla Toolsets 1.1.3
		variablepaxels: VariablePaxels 1.14 Pre-Release 5-0.0.1
		waila: Hwyla 1.9.16
		whilewewait: While We Wait 1.2.1
	Launched Version: fabric-loader-0.4.8+build.155-1.14.3
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/vanilla-improvements-v1-14-2-2-1556743736.zip, file/AudioCraft.zip (incompatible), file/AntiqueAtlasExtra.zip (incompatible), file/smooth-edges-1561721161.zip, file/VisualEnchantments1.14_v5.1.zip, file/2011+Hurt+Sounds.zip, file/Shield+Banners++.zip, file/Cauldron+for+brewing+potions+(WS)+v2.0+(1.14).zip, file/Better+Leaves+v2.0-1.14+.zip, file/KSAO_UI_4.0.zip, file/Additional Entities 1.13, file/ImprovedFoxes.zip, file/Ethnicity+1.14.zip, file/Modern Art Set (1.14+)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

**Comment by Barerock** [comment]
Having this as well, however, the game crashes on loading new textures of any kind for me. 
Easiest fix: disable this mod or Opti- mods.

**Comment by deli73** [comment]
seems to be a crash on reloading resources at all. i don't have optifine and this is still happening for me??
