### ISSUE TITLE
Crash rendering markers with illegal names

### ISSUE THREAD

**Issue by Zekrom64** [Hunternif/AntiqueAtlas#239]
I have been using the 1.12.2 version of Antique Atlas as part of the Sevtech: Ages modpack with a group of other players, and had an issue where my client would crash when attempting to render the name of a marker in the map. I traced the issue to the marker having characters that interfere with the call to `String.format` in `Marker.getLocalizedLabel`, namely the `%` character (The marker was named "100% Aluminum"). The only way to solve this issue was to edit the marker NBT to change the name.

There should be some way of escaping characters that interfere with the formatting or they should not be allowed to be added to a name.

[crash-2019-07-28_22.42.58-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/3440157/crash-2019-07-28_22.42.58-client.txt)

**Comment by tyra314** [comment]
Shouldn't that be fixed now with: 5f1a2397aa9d011f0bcbacc4fe67825af420f9a7 ?

**Comment by Hunternif** [comment]
Yes, but it's not released yet
