### ISSUE TITLE
Atlas doesn't work at coordinates around 10,000,000

### ISSUE THREAD

**Issue by Hunternif** [Hunternif/AntiqueAtlas#244]
The map is empty, and log spams message "TileGroup tried to set tile out of bounds".

This can be solved by making tile coordinates `int` instead of `short`. However, network packets currently write `short`. In case of a version mismatch between client and server, the client will read garbage. Therefore for longer coordinates a new packet is needed.

_Premature optimization is the root of all evil._

**Comment by tyra314** [comment]
This is still a thing in the Fabric version. I need to cherry-pick that commit and massage it until it works there also.
