### ISSUE TITLE
Suggestion: Option to designate items that count as atlas for the item in hot bar needed to activate minimap:

### ISSUE THREAD

**Issue by SirAron111** [Hunternif/AntiqueAtlas#250]
SO here is the thing I have a story driven modpack and in a way all information all books etc are all stored in a special item that can access these. I added the atlas as well and the atlas works great if the item is turned into that atlas it displays the map and all but what I would like to be able to do is add all forms of that special items into a list so the minim map still stays around as long as said key item is still there.

Having an empty list where people can add things like “akashictome:tome” or “mod321:specialmapitem_1” etc would be fine if that’s possible.

I bet this could be used by other packmakers as well.

**Comment by Hunternif** [comment]
Does it have to be an item? If you set the option `itemNeeded: false`, then every player will have an atlas automatically, accessible at the press of a button.
