### ISSUE TITLE
Overlay not displaying correctly

### ISSUE THREAD

**Issue by sattrnn** [Hunternif/AntiqueAtlas#251]
OS: MacOS 10.14.5
Minecraft Version: 1.14.4
Antique Atlas Version: 5.1.3 for Fabric

I enabled the overlay for the atlas within the config however once I held it the overlay was blank. I can open the atlas and everything shows up normally but the overlay is currently non-functional. 
<img width="1440" alt="Screen Shot 2019-11-07 at 9 40 36 PM" src="https://user-images.githubusercontent.com/56606464/68453062-56779600-01a9-11ea-8bfa-dacc298290fe.png">

**Comment by Danklor** [comment]
This is the same for me with--
MacOS 10.14.6
MC 1.14.4
Fabric 0.6.3-b168
Fabric API 0.4.1-b245
Cotton 1.0.0-rc3

**Comment by tyra314** [comment]
Fixed in 5.1.4-fabric.
