### ISSUE TITLE
[1.15pre] probably very broken

### ISSUE THREAD

**Issue by Yoghurt4C** [Hunternif/AntiqueAtlas#252]
most likely just the tip of the iceberg https://pastebin.com/A62MctXm
also, a small tipoff on the cotton dep from a verified source:tm:;
![image](https://user-images.githubusercontent.com/11313954/69449272-97f06f80-0d6b-11ea-8dc5-26066d388137.png)

**Comment by tyra314** [comment]
That link doesn't work for me

**Comment by Yoghurt4C** [comment]
I guess hastebin decided to eat it, https://pastebin.com/A62MctXm

**Comment by Yoghurt4C** [comment]
just fyi: cotton-config is now (for the time being?) incompatible with the latest jankson most other mods use, so antique atlas is now broken by proxy

**Comment by tyra314** [comment]
Are you talking about the 1.15-pre branch or the 1.14 release version?

**Comment by Yoghurt4C** [comment]
I've only tested 1.15pre, unsure if this affects 1.14

**Comment by tyra314** [comment]
I think that was fixed in the release version.
