### ISSUE TITLE
Minimap is empty

### ISSUE THREAD

**Issue by Juuxel** [Hunternif/AntiqueAtlas#255]
> Game version: 1.15.1-pre1
> Antique Atlas version: 5.1.4 (the version in the Bee Merry modpack by Yoghurt4C)

The minimap is completely empty even when the atlas has contents.
![](https://cdn.discordapp.com/attachments/507982463449169932/655784663444619284/2019-12-15_16.53.51.png)

**Comment by tyra314** [comment]
This is fixed in the actual release.
