### ISSUE TITLE
Malware detected

### ISSUE THREAD

**Issue by Roankuijsters** [Hunternif/AntiqueAtlas#257]
My avast antivirus detects malware a trojan in the .jar.

**Comment by osipxd** [comment]
Check on https://www.virustotal.com/ 
For example, [here](https://www.virustotal.com/gui/url/5393e1c772e9f18e05dc3adcfb56fa313adb323e30fd7b3ad78e467667d3b89b/detection) results of test for 5.1.4-fabric.

**Comment by tyra314** [comment]
I've check several files provided on Curseforge and non of them raised any issue. Thus, I believe that this is a false positive of your antivirus software. So I'm going to close this.
