### ISSUE TITLE
Game crash: Ticking player

### ISSUE THREAD

**Issue by RisingInIris2017** [Hunternif/AntiqueAtlas#259]
## Forge Version:
14.23.5.2847
## Mod Version
4.6.3
## Singleplayer or Multiplayer
Multiplayer, using [Mohist](https://github.com/Mohist-Community/Mohist)
## Crash report
https://paste.ubuntu.com/p/ZZ2hWpSjFx/

**Comment by tyra314** [comment]
There won't be another 1.12 update, so I'm closing this.
