### ISSUE TITLE
[1.12.2] Minimap overlay doesn't show up at all

### ISSUE THREAD

**Issue by talesofmabria** [Hunternif/AntiqueAtlas#270]
Unsure of why this is happening.  I'm guessing it might be a mod conflict somehow?
Right-clicking with the book works fine, but the minimap doesn't show whatsoever.

**Comment by Hunternif** [comment]
I changed it to be disabled by default, but  you can enable it in mod settings. If I remember correctly, Forge settings UI hasn't been working since 1.12, so you may have to edit the config file `.minecraft/config/antiqueatlas/atlas_overlay.cfg`, set the option `enabled=true`

**Comment by talesofmabria** [comment]
Ohhh!  I gotcha, thanks!
