### ISSUE TITLE
recipe change, enchantment table-esque book model, integrate cartographer maps in atlas and cave mapping

### ISSUE THREAD

**Issue by kuroyure** [Hunternif/AntiqueAtlas#273]
this is my choice mapping mod for its immersive nature and beautifull textures so id like to share a few ideas i had, firstly the recipe
one book, 7 empty maps and a compass, the book would use scribing tools (similar to the thaumcraft ones) and paper(a set ammount to generate a x chunk radius in the map.
 The next idea, make the atlas have the enchantment table's book as a model and appear open in your hand as you hold it, with the pages decipting what goes on in the minimap, a compass would hang from a string on the book.
 Some sort of cave maping atlas to help cave navigation or even an upgrade to your atlas using an underground map that would only be obtained by trading with a cartographer, using 8 of these on a crafting table with your atlas.
 Finnaly the ability to integrate cartographer bougth maps on your atlas to be able to find the structures they lead to seem like a good idea to me.

**Comment by tyra314** [comment]
This issue is mostly done. The recipe was changed to the format proposed in #241. The rendering was done a few versions past. And the integration with the cartography table is out as well. I'm not sure about cave mapping though. Maybe I'll give this more thought once 1.17 hits.
