### ISSUE TITLE
[1.16.3] Game crash during load

### ISSUE THREAD

**Issue by crabdancing** [Hunternif/AntiqueAtlas#275]
During early game load it crashes, on 1.16.3. See log [here](https://paste.ee/p/x9fzy).

**Comment by kalucky0** [comment]
Same here

**Comment by StefanJanssen95** [comment]
I've got the same error here.

**Comment by YourFavDabbler** [comment]
@alxpettit @StefanJanssen95 

Did y'all make sure that y'all had the cotton config installed? It was just crashing for me until I looked at my fabric loader log and noticed that I had to have cotton installed to have this mod function. I don't know why the dependency wasn't noted, but it worked for me. Then again, I am using MultiMC

**Comment by StefanJanssen95** [comment]
@YourFavDabbler if with Cotton config you mean: https://www.curseforge.com/minecraft/mc-mods/cotton
Then yes I do.

**Comment by gosthrider** [comment]
Same thing here... The cotton API is not helping.
Please @YourFavDabbler could you be more precise about the cotton config files ?

**Comment by SimonYuuki** [comment]
I have the same problem but in 1.16.4 [Here](https://paste.ee/p/9NICP)

**Comment by ghost** [comment]
same

**Comment by tyra314** [comment]
There is no released version compatible with 1.16.3/1.16.4 and this lacks crash logs now.

Try the current head of the fabric-1.16 branch, if you're not patient.

**Comment by StefanJanssen95** [comment]
The latest released fixed the issue 👍

**Comment by tyra314** [comment]
Thanks for reporting back,

**Comment by SimonYuuki** [comment]
Yes ! thanks you ! :)
