### ISSUE TITLE
Rendering issues with Canvas mod

### ISSUE THREAD

**Issue by ghost** [Hunternif/AntiqueAtlas#280]
![image](https://user-images.githubusercontent.com/75881942/103444335-8ec51800-4c78-11eb-84ef-4e93d7be1434.png)
![image](https://user-images.githubusercontent.com/75881942/103444339-984e8000-4c78-11eb-93a6-1585825203fe.png)
second picture - white colors appear when changing the map scale

**Comment by tyra314** [comment]
The second picture is fixed with the commit 52c731a777eddeda9fbfdb3e78faaaf33c7f067b.

**Comment by Vulcanoz** [comment]
Fixed. v5.4.2 Fabric. 
![image](https://user-images.githubusercontent.com/75881942/104842758-e0f07500-58d7-11eb-9d2d-1797e2e5160e.png)

**Comment by ghost** [comment]
Fixed. v5.4.2 Fabric.
![image](https://user-images.githubusercontent.com/75881942/104842815-53f9eb80-58d8-11eb-95cf-c225f1ab7785.png)
