### ISSUE TITLE
Fabric Waystones Compatibility

### ISSUE THREAD

**Issue by SylisMC** [Hunternif/AntiqueAtlas#281]
~Forge atlas was always good about being compatible with warp like mods
Id love to see the fabric version pair with fabric waystones just like forge atlis paired with forge waystones~

I just realized that was an entirely different mod, [Atlas Extras](https://www.curseforge.com/minecraft/mc-mods/atlas-extras) was an awesome mod for antique atlas that added integration with [waystones](https://www.curseforge.com/minecraft/mc-mods/waystones) and [signposts](https://www.curseforge.com/minecraft/mc-mods/signpost) I would love to see these features come to antique atlas. with compatibility with [fabric-waystones](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)

- [ ] fabric way stones render on map automatically
- [ ] hud option available

**Comment by tyra314** [comment]
While I definitely think more mod support is better, I think this should be an external mod as well. I keep this as an idea, but I'd like to improve the "vanilla" experience first.
