### ISSUE TITLE
Curio support

### ISSUE THREAD

**Issue by SylisMC** [Hunternif/AntiqueAtlas#282]
Id love to see support for [Curio](https://www.curseforge.com/minecraft/mc-mods/curios) adding a designated slot for the atlas with a keybind to open it

**Comment by tyra314** [comment]
Thank you for your idea, but I don't think a Curio slot fits the vision of this mod. Especially now, as the atlas overlay gets rendered like a vanilla map when looking down.

Feel free to convince me otherwise.

**Comment by SylisMC** [comment]
I think this might be something that would fit better lumped in with [issue 281](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/281)

I love having a tangible object as a minimap, but i also love the convenience of having it up and open. even if the keybind renders you pulling the map out and holding it in front of your face.

**Space Is an issue** 

- As you pile the mods on, inventory space gets more and more full of items like maps and trinkets, materials, etc. the mod mods you have, the harder it gets to manage inventory space. you just end up with too much junk, a special compass from x mod, a telescope from y mod, an atlas from this mod. some plants for z mod a crap not of ores from mods L,M,N,O,P. space becomes an issue fast, and the enjoyment of exploring is continuously interrupted by "quick dumping trips home". its kinda like when youtube place ads every 30 seconds in a video you're trying to watch haha

- Vanilla mining trip.
you are likely to only have a small handfull of blocks/items, your basic mining gear along with some diamonds, and iron you picked up along the way. you didn't bother stopping for coal because that stuff is everywhere. and you already finished your rail system ages ago. you found a dungeon along the way and grabbed scored some saddles and nametags along the way, life is good and you are happy

- Modded mining trip
You have your spelunking gear and some extra items that might come in handy from all your mods. and you're ready to go. you grab some iron and happen to find some tin along the way, you remember needing it to make this really cool item you wanted to try, you run into a dungeon along the way and both chests are soo full from all the lootable additions from all the mods you're packing. It takes some time to sort through everything, thankfully a creeper didn't sneak up behind you in your 10 minute sorting errand, and luckily there were a few duplicate items you were able to stack, so you still have enough space for some diamonds and this new ruby gem you need for smithing. after some mining you find your diamonds and rubies, luckily you noticed that you didn't pick them up when you mined them, now comes the sorting again, you've already sorted your inventory a few times, everything you have you really wanted to keep. you suppose you could throw out your spyglass and just make a new one when you get back home, but that's not enough, you need your atlas to find your way home so you figure you'll have to throw out a stack of iron for these rubies, you are not happy about it but its a sacrifice you'll have to make.

- You only have 9 active Hotbar slots, one for a sword, efficiency pick, fortune pick, shovel, torch, water bucket, food, maybe a potion of fire resistance, slots fill up fast.

I understand that saving one item slot doesn't seem like a lot but when you have a backpack, a portabale crafting table, a portable enderchest, a totem of undying, a heartbond necklace (used for a vanilla friendly teleporting system) those slots pile up fast (all of them are curio compatible) saving you upwards of 6 slots. again, it's only an option, if a user doesn't install curio they can still just use the map as normal.

I really enjoy the aesthetic of the atlas but could see the lack of an option for a GUI to make people lean towards other alternatives. If the option for a hud is at least available, I wouldn't think it would drive people who don't want a hud away from using A-Atlas, but I definitely think more people would use the mod

If you wanted, the client could even check with the server if huds are allowed. allowed more control over the users intended experience. More options is never a bad thing

**Comment by KnightMiner** [comment]
As a comment from a more vanilla perspective, Minecraft is balanced around tradeoffs in a lot of places. Many enchantments are incompatible for instance, so you have to choose mending or infinity on your bow for example, and you cannot have both high defense and an elytra in your chestplate slot. I think in that sense its acceptable that using an atlas requires you to give up something. Would you rather have a map of the area, or an extra hotbar slot? I think the solution with modded is to use a backpack to save inventory space or one of the toolbelt mods that grants you additional hotbar slots rather than removing the tradeoff of using an atlas.

**Comment by tyra314** [comment]
Technically speaking, an atlas already saves you a ton of inventory space. If you wanted to do, what an atlas gives you with pure vanilla mechanics, you'd need empty maps, several unstackable maps, and a compass only for the map drawing. Then you'd need banners that are either prenamed und thus unstackable, or an anvil to name them on the spot. 

Having said that, I don't see space as a problem, to begin with, especially in modded. Get yourself an ender chest full of shulker boxes, which gives you about 750 stacks of inventory space. And that's vanilla only. I bet there are even crazier things possible in modded. If you still need to save one more place, why not use the `itemNeeded` config options that allow you to just hit `M` for the atlas.

Given this, I can't make the case for a curio slot.

**Comment by SylisMC** [comment]
That actually causes the game to crash. made a repoty [here](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/286)

**Comment by tyra314** [comment]
I appreciate the suggestion, but as explained, I don't see it fitting.
