### ISSUE TITLE
[Question] How do I add custom markers? 1.12.2

### ISSUE THREAD

**Issue by Kirin92** [Hunternif/AntiqueAtlas#283]
Hey~
I want to ask how do I add custom markers to AntiqueAtlas for Minecraft 1.12.2?
Of course I read the wiki and tried to follow the tutorial but everytime I change the config, it overwrites the config file.
The resourcepack I use is the AntiqueAtlasExtra pack with the colored biomes. I thought I could edit it and add a new folder "markers".

What should I do? 
It would be good if there were a newer tutorial.
I really want to add new markers I made.
Thank you!

**Comment by AustinMajeski** [comment]
I figured it out.

Everyone (including myself) was typing their JSON in an invalid way.

\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\

	1.	Move this resourcepack into your "resourcepacks" folder.
	2.	< any order >
		a.	Open Minecraft and select to use this resourcepack.
		b.	Copy the contents of the file "markers.json.example.txt", 
			located inside this resourcepack, into the file "markers.json"
			 located inside your minecraft directory at
			"...\.minecraft\config\antiqueatlas".
	3.	Close Minecraft.
	4.	Open Minecraft.

Note:    The resourcepack must be selected for use when Minecraft is launched so the textures/icons can be loaded.
		
\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\:::\\


Sample image:  https://imgur.com/gallery/6kobT1z
Download:  https://www.mediafire.com/file/2txc35fwbix0yei/Antique_Atlas_Custom_Icons_Example_-_%25281.12.2%2529.zip/file

**Comment by Kirin92** [comment]
OMG thank you so much! It works! Now I can add my markers :D you're a life saver
