### ISSUE TITLE
Faulty config options?

### ISSUE THREAD

**Issue by SylisMC** [Hunternif/AntiqueAtlas#289]
Unless I'm misunderstanding, these config options don't appear to work at all
`"alignRight": true,`
`"alignBottom": true,`
`"width": 232,`
`"height": 163,`
I had assumed they were supposed to be for the minimap but they dont appear to have an effect on any of the maps

If these are not intended for the minimap option, some more config options would be greatly appreciated. traditionally, minimaps are often in the top right corner and id personally like to be able to put it there.

**Version** (1.16.4)
jumploader-2.1.2
antiqueatlas-5.4.0-fabric
fabric-api-0.28.4+1.16

**Comment by tyra314** [comment]
Sorry, these config options seem to be thrown under the bus in some refactoring. I'm not sure if they are getting removed, or fixed now. Meanwhile, you can use xPosition and yPosition in the config.

**Comment by mosharky** [comment]
So are there no plans to fix this? I really want to incorporate this mod into a modpack I'm working on, but I can't really do that comfortably with the minimap being on the top-left by default (on forge at least)

**Comment by AmyMialee** [comment]
> Sorry, these config options seem to be thrown under the bus in some refactoring. I'm not sure if they are getting removed, or fixed now. Meanwhile, you can use xPosition and yPosition in the config.

is there any alternative for the size? it's unbearably small for me as it stands.

**Comment by tyra314** [comment]
For the size, you can try setting the `GUI Scale` in the video settings of Minecraft, IIRC the minimap and atlas scale with that.

**Comment by AmyMialee** [comment]
> For the size, you can try setting the `GUI Scale` in the video settings of Minecraft, IIRC the minimap and atlas scale with that.

This isn't a reasonable option, since then the rest of the gui is overwhelmingly large, only the atlas is too small.

**Comment by tyra314** [comment]
I'm sorry that this isn't an option for you. It was meant as a workaround. Though, can you attach a screenshot with the atlas size and maybe an outline for the size you would feel comfortable with? Maybe the scaling is off for you anyways.

**Comment by tyra314** [comment]
As the minimap was replaced with the vanilla-like rendering in 6.0.0, this issue is obsolete now. closing.
