### ISSUE TITLE
Minimap should only open when the atlas is held in the offhand

### ISSUE THREAD

**Issue by FewerFlaws** [Hunternif/AntiqueAtlas#290]
This is probably best as a configurable option, but I would really like it if the minimap only displayed with the atlas in the offhand.  Currently it's too easy to get the map flickering on the screen when scrolling past the atlas.

**Comment by tyra314** [comment]
What do you mean with flickering?

**Comment by FewerFlaws** [comment]
I mean that it appears briefly and then disappears.  This is not a bug, just a natural consequence of using the scroll wheel to pass over it in the inventory belt.

**Comment by FewerFlaws** [comment]
Another solution to the same problem would be a configurable delay, much like how it takes a bit of time to visually put one item away and pull out another.
