### ISSUE TITLE
Right-clicking with the atlas open should close the atlas

### ISSUE THREAD

**Issue by FewerFlaws** [Hunternif/AntiqueAtlas#291]
Right now right-click does the same thing as left click and escape is necessary to close the atlas.  It would feel much more natural if right-click closed the atlas so you could quickly open and shut it =]

**Comment by tyra314** [comment]
While I see your point, I wonder why you feel a right-click close would be more natural? I tried to think of items in vanilla that open a gui on right-click. The only items I came up are Book and Quill, and signs. Both can't be closed with a right-click. Though they have a dedicated close button.

**Comment by FewerFlaws** [comment]
It's more natural because the atlas is the kind of thing a person would want to peak at regularly.  Right click to open, then right click to close.  Just like how you can peak at your inventory by clicking 'e' twice.

The dedicated close button you mentioned works well with the books because it _offers_ you an obvious way to close the book interface.  Right click to close the books would be fine, perhaps an enhancement, but it's not a clear improvement because peaking at books is not a normal thing.  You open them to write or read.  The atlas is more graphical; its information is more compact.  This allows the user to glance at it and retain a usable amount of information.

Escape is problematic for two reasons.  First, it's far away on the keyboard.  Second, its one of those 'meta' keys, which doesn't always do what you want because it has a wide variety of things it **might** do.  Hitting escape will always close something.  The thing it closes is often the game environment, allowing access to the menu.  Escape is a go-to, but it's not an immersive first choice.

Just my two-cents.  I think right-click to close would be an improvement.  A dedicated close button would also be an improvement =]
