### ISSUE TITLE
The Atlas, when in both hands, has a rendering issue whenever you have Invisibility.

### ISSUE THREAD

**Issue by InvitedRhino683** [Hunternif/AntiqueAtlas#293]
Now, this isn't gamebreaking per say, and it certainly doesn't crash your game, and it is almost certainly never going to be experienced in-game, but I feel like it should be reported none-the-less. It never happens without invisibility, atleast with how much I've tested on the new release, so yeah. It's gotta something with the rendering. I do happen to have S/L/P in my pack, so that may be also happen to be the case, as this is a rendering issue.

Video evidence:
https://drive.google.com/file/d/1Z5nVHH03ZjC4oFB2dqaaSLuNtVSfN1to/view?usp=sharing
Log File for further studying:
[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/5792003/latest.log)

Versions:
Fabric - 0.10.8
Minecraft - 1.16.4
Antique Atlas - 5.4.1
MultiMC - Version 0.6.12, Development Version 1496

**Comment by tyra314** [comment]
I think that is related to #280, if not the same underlying issue.

**Comment by tyra314** [comment]
That issue is so strange... I fixed the z-fighting, but now the atlas is very dark when you have the invisibility potion.

But when you also apply a night vision potion, it's gone. When you apply milk to remove all potion effects, it works. The next night vision potion after that has no effect what so ever. I'm so confused.

**Comment by InvitedRhino683** [comment]
Oof. I don't know what is causing the issue is here, do you think you could quickly explain it?

**Comment by tyra314** [comment]
I've no idea either.

**Comment by InvitedRhino683** [comment]
Damn. That must suck. I can't help you here, maybe the people over at JellySquid's Discord might be able to help?
