### ISSUE TITLE
Crash on server load

### ISSUE THREAD

**Issue by Nihilhalla** [Hunternif/AntiqueAtlas#295]
Server error:
java.lang.RuntimeException: Attempted to load class kenkron/antiqueatlasoverlay/event/FirstPersonRendererEvent for invalid dist DEDICATED_SERVER

Server log:
https://pastebin.com/VeHyUbtu

Expected behavior:
Server loads.

Steps to reproduce behavior:
Add Antique Atlas to server mods folder, start server.

Thanks for your time! I hope this can be easily fixed as I love this mod!

**Comment by tyra314** [comment]
Fixed in #304
