### ISSUE TITLE
Antique Atlas overlay mod setting doesn't show up 1.16.4

### ISSUE THREAD

**Issue by captinwill** [Hunternif/AntiqueAtlas#299]
My problem is simple, the antique atlas overlay mod setting doesn't show up is 1.16.4.

**Comment by captinwill** [comment]
Also i ment forge

**Comment by kenta91** [comment]
you mean the overlay like a mini map right? you have to enable this by yourself in the config files. @captinwill

**Comment by tyra314** [comment]
I assume this is fixed.
