### ISSUE TITLE
Cant craft anything 1.16.4 forge

### ISSUE THREAD

**Issue by captinwill** [Hunternif/AntiqueAtlas#300]
i have been playing this world and i decide to get this mod and then when i go to craft the atlas of anything my game crashes here is log 
[crash-2021-01-15_14.30.30-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/5822595/crash-2021-01-15_14.30.30-client.txt)

**Comment by captinwill** [comment]
and i used vanilla crafting table

**Comment by tyra314** [comment]
Duplicate of #297
