### ISSUE TITLE
Shaders and Antique Atlas layer bug

### ISSUE THREAD

**Issue by ensapra** [Hunternif/AntiqueAtlas#301]
Using, some shaders, specific Sildurs Vibrant Shaders v1.281 and Simplicissimus_v1.2 make the map render under ice objects. I don't know if this is an issue of this mod or shaders, but since it only happens with Antique Atlas type of mod I suppose happens only on this one.

I'm using the latest AntiqueAtlas version, currently: antiqueatlas-5.4.2-forge.jar, using 1.16.4-forge-35.1.28. I guess it's a layer issue since with normal maps it doesn't happen.

![image](https://user-images.githubusercontent.com/61149758/104815055-8b9e6000-5812-11eb-8f62-5c33a91faecc.png)
_Antique Atlas_

![image](https://user-images.githubusercontent.com/61149758/104815174-44649f00-5813-11eb-95d1-52fea62385c3.png)
_Normal Map_

**Comment by tyra314** [comment]
This probably has to do with the change I made to fix #280 and partly #293. In particular, I suspect [this](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/commit/025421b331d67033f9561c088a1c0b705bec4813#diff-00c5a50629c2d251e7797a072fe1bf81635409aecacd6d37a4da4379f7c248e2R104)

**Comment by tyra314** [comment]
Seems it also happens without shaders: #325
