### ISSUE TITLE
Atlas only works in the main hand - not in the off-hand.

### ISSUE THREAD

**Issue by K0-RR** [Hunternif/AntiqueAtlas#307]
Should work in both hands.
 - Minecraft: 1.16.5
 - Fabric Launcher: 0.11.1
 - Fabric API: 0.29.4
 - AntiqueAtlas: 5.4.2-fabric

**Comment by K0-RR** [comment]
Also, what is this? 'There is now a minimap that is enabled by default if you put an Atlas into the off-hand slot.' I don't see a minimap anywhere. Is it not ported to fabric?

**Comment by tyra314** [comment]
> 
> 
> Also, what is this? 'There is now a minimap that is enabled by default if you put an Atlas into the off-hand slot.' I don't see a minimap anywhere. Is it not ported to fabric?

There is a config option to enable the minimap.

**Comment by tyra314** [comment]
> Should work in both hands.

What do you mean with works?

**Comment by ITCMD** [comment]
I've had this issue too despite enabling it: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/324
