### ISSUE TITLE
Atlas should have a limit to how much terrain can store.

### ISSUE THREAD

**Issue by K0-RR** [Hunternif/AntiqueAtlas#308]
One atlas should store data of let's say 2000x2000 blocks to force a player to make a new one.

**Comment by tyra314** [comment]
Thank you for your ideas, but that doesn't sound like a fun mechanic.

First of all, why should there be an limit? (Technically, there is an limit, but that's a mood point).

Then, suppose there is a limit. When travelling, players would have to constantly swap atlases and search for the current one. Doesn't sound fun to me. I could go on, but overall I can't image a situation, where this would lead to better gameplay.

**Comment by K0-RR** [comment]
Vanilla maps have a limit. Books have a limit. If this is just a book with compass then a limit just makes sense. This would nerf this mod and bring some realism.
