### ISSUE TITLE
Village detection does not work

### ISSUE THREAD

**Issue by sheng-ri** [Hunternif/AntiqueAtlas#311]
**Describe the bug**
Antique Atlas don't show the village.

**To Reproduce**
1. type /locate village
2. run the command.
3. open Antique Atlas

**Expected behavior**
show the village.

**Screenshots**

**Forge version information (please complete the following information):**
 - Minecraft: [e.g. 1.16.5]
 - Forge: [e.g. 36.0.7]
 - AntiqueAtlas: [e.g. 5.4.4-forge]

** Server side version information: **
I'm running Arclight-1.16-1.0.12-SNASHOT
Forge: 36.0.1
Minecraft: 1.16.5

**Additional context**

Arclight is a Bukkit server implementation utilizing Mixin.

https://github.com/IzzelAliz/Arclight/tree/1.16/

[Antique Atlas Transformer]: Patching StructureStart...
[Antique Atlas Transformer]: Patch 1 failed
[Antique Atlas Transformer]: Patch 2 was successful
[Antique Atlas Transformer]: Patching StructureStart#func_230366_a_ failed
[11:38:32] [main/WARN] [mixin/]: @Final field field_76203_h:Ljava/util/Map; in supplementaries.mixins.json:MapMixin should be final
[Antique Atlas Transformer]: Patching StructureStart...
[Antique Atlas Transformer]: Patch 1 failed
[Antique Atlas Transformer]: Patch 2 was successful
[Antique Atlas Transformer]: Patching StructureStart#func_230366_a_ failed
[Antique Atlas Transformer]: Patching CraftingResultSlot...
[Antique Atlas Transformer]: Patch 1 was successful
[Antique Atlas Transformer]: Patching CraftingResultSlot#onCrafting was successful

**Comment by sheng-ri** [comment]
Why not add three labels version,forge and fabric.
Distinguish them by color.

**Comment by tyra314** [comment]
> 
> 
> Why not add three labels version,forge and fabric.
> Distinguish them by color.

Because not all combinations exist

**Comment by tyra314** [comment]
Fixed in 6f9632b6551b9088eb2a123aeea224ed8f0dec73
