### ISSUE TITLE
Error starting the game

### ISSUE THREAD

**Issue by ghost** [Hunternif/AntiqueAtlas#312]
Error starting the game

 - Minecraft: [1.16.5]
 - Fabric Launcher: [0.11.1]
 - Fabric API: [0.29.4]
 - AntiqueAtlas: [5.4.3-fabric]
 
[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/5882147/latest.log)

**Comment by tyra314** [comment]
Fixed in a5614b5c4d7a80148d4f3c7987e175ca265b935b
