### ISSUE TITLE
Water Bug : Forge Version 1.16.4

### ISSUE THREAD

**Issue by SheltieChan** [Hunternif/AntiqueAtlas#313]
The atlas is seemingly under the water when held while looking at the water.

![image](https://user-images.githubusercontent.com/56488659/106722181-a3783100-65d3-11eb-9fba-446a7c57bcd1.png)

**Comment by tyra314** [comment]
Duplicate of #301

**Comment by tyra314** [comment]
Are you running with Optifine?

**Comment by SheltieChan** [comment]
Yes
