### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Taknax** [Hunternif/AntiqueAtlas#315]
Alternative colored mapdesign in minecraft style. For those, who dont want to have the zelda theme.
Its the best minimap i ever played. Totally suvival fitting. After some playtime i relized i would like a map with more minecraft style symbols. This could be toggable. For the coloring part. Maybe an upgrade for the book to enchant the color.
Ty for your amazing work!

**Comment by tyra314** [comment]
There's Golrith's colored texture pack. In general, you're requesting a texture pack. While it might not be satisfactory for you, I don't think adding a second texture pack is time well spent for us. Though, I'd highly appreciate any texture packs and would them advocate on the mod page as well.
