### ISSUE TITLE
When ever i right click my game crashes 

### ISSUE THREAD

**Issue by Spike8Plays** [Hunternif/AntiqueAtlas#317]
When ever i right click holding the atlas the game crashes

This is the crash error -The game crashed whilst rendering screen
Error: java.util.IllegalFormatConversionException: d != java.lang.String
Exit Code: -1

It happens everytime

Im Playing on Minecraft 1.12.2

**Comment by tyra314** [comment]
Please provide the crash log

**Comment by Jjae24** [comment]
Hello I'm having the same problem on the same version
This is my crash report

[crash-2021-06-04_01.47.56-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/6597095/crash-2021-06-04_01.47.56-client.txt)

**Comment by tyra314** [comment]
Update AA, it is fixed in the latest version available for 1.12.2
