### ISSUE TITLE
Fix Fabric API version dependency

### ISSUE THREAD

**Issue by BluePixel1708** [Hunternif/AntiqueAtlas#319]
The game crashes on launch whenever i try to use antique atlas on modded (it has happened before, so ignore the biome locator message)
[crash-2021-02-11_16.38.41-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/5968879/crash-2021-02-11_16.38.41-server.txt)

**Comment by tyra314** [comment]
You need a newer Fabric API, your version is to old.

*edit: In particular, anything newer than 0.28.0
