### ISSUE TITLE
alignRight and alignBottom config options not working

### ISSUE THREAD

**Issue by Limeyhoney** [Hunternif/AntiqueAtlas#321]
**Describe the bug**
Setting the alignRight and alignBottom to true in the config has no effect on the minimap overlay position.

**To Reproduce**
1. Enable minimap
2. Change alignRight to true in config
2. Change alignBottom to true in config
3. Launch a minecraft world
4. Open an atlas
5. Observe that the minimap is still aligned to the top left

**Expected behavior**
The mini map should be aligned to the bottom right.

**Screenshots**
With both alignRight and alignBottom set to true, offsets set at 2 for both x and y.
![2021-02-12_20 22 19](https://user-images.githubusercontent.com/25417001/107839229-0dc96800-6d70-11eb-9f18-91fefd43cd70.png)

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.0.9
 - AntiqueAtlas: 5.4.4

**Comment by jajajafeti** [comment]
I wanted to do the same, can aprove.

**Comment by tyra314** [comment]
Duplicate #289
