### ISSUE TITLE
[Crash] Ticking Memory

### ISSUE THREAD

**Issue by InteJason** [Hunternif/AntiqueAtlas#322]
**Describe the bug**
I generated a new world, and it crashed immediately. Can't join that world ever since.

**To Reproduce**
The problem happens randomly. It's hard to replicate the problem everytime. But here goes:
1) Create a world
2) Crash: https://paste.ee/p/ZfDEt

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.4
 - Forge: 35.1.37
 - 5.4.4

**Additional context**

**Comment by stanlexgreenson** [comment]
That's happening to me too, with the same versions. But in my case it doesn't happen randomly it happens every time I create a world.

**Comment by tyra314** [comment]
Duplicate of #314
