### ISSUE TITLE
Map is translucent when in front of water.

### ISSUE THREAD

**Issue by darkknight97578** [Hunternif/AntiqueAtlas#325]
The map becomes translucent when in in front of water, or the nether portal. It still shows the book with all the images, its just the background that changes.

Works normally above blocks
![2021-02-24_00 08 21](https://user-images.githubusercontent.com/79567519/108967834-d642a180-7634-11eb-8285-b23437c06bf5.png)

Is weird above water
![2021-02-24_00 08 41](https://user-images.githubusercontent.com/79567519/108967847-db075580-7634-11eb-9587-bc63496608cc.png)

**Comment by tyra314** [comment]
Seems a duplicate of #301. I assume you're using Optifine?
