### ISSUE TITLE
Crash with ItemNeeded config setted to false

### ISSUE THREAD

**Issue by LeoBeliik** [Hunternif/AntiqueAtlas#330]
**Describe the bug**
Game crashes when I open the map with the keybinding and try to close it, this happens with the config option "itemNeeded = false", it also happens were I have or not the book in my inventory.

**Forge version information (please complete the following information):**
 - Forge: 36.0.42
 - AntiqueAtlas: 5.4.4
 
**Additional context**
https://gist.github.com/LeoBeliik/3733b96a8aa08461530219a73dd01f25

**Comment by Vinjul1704** [comment]
I can confirm this happens for me too, using Forge 36.1.0. The minimap seems to work, but trying to open the fullscreen map crashes the game.

**Comment by tyra314** [comment]
Fixed in #359

**Comment by Vinjul1704** [comment]
Awesome, thanks a lot!
