### ISSUE TITLE
Game Crashes when Right clicking the Antique Atlas on FORGE

### ISSUE THREAD

**Issue by SHXRKIEgg** [Hunternif/AntiqueAtlas#334]
**Describe the bug**
Game Crashes when Right clicking the Antique Atlas on FORGE

**To Reproduce**
1. Create Atlas
2. Right click Atlas
3. Crash

**Expected behavior**
Game shouldn't crash

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.0 (Latest)
 - AntiqueAtlas: antiqueatlas-5.4.4-forge.jar (Latest forge version)

**Additional context**
Using the Better Minecraft Modpack
[crash-2021-03-18_15.01.32-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/6161224/crash-2021-03-18_15.01.32-client.txt)
[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/6161226/latest.log)

Hope you can help me pinpoint why it crashes

**Comment by tyra314** [comment]
The crash is caused by FancyMenu.
