### ISSUE TITLE
can't add new biome types in texture packs

### ISSUE THREAD

**Issue by Just2Github** [Hunternif/AntiqueAtlas#338]
I tried using the texture pack made by Golrith from forge 1.12 on the forge 1.16 version with biomes o plenty. While the normal biomes get their new (coloured) icons, the bop icons don't show up at all. I suspect this has to do with the fact that the config file for the 1.16 forge version is different from the 1.12 version, but I wonder if it is still possible to add in biome ID's and assign icons to them directly through the resourcepack itself.

**Comment by tyra314** [comment]
Yeah, this has been lingering for a while. In the meantime, I've rewritten the whole stuff to completely use resource packs. For now, this is only part of the Fabric code, but will eventually trickle down to forge. 

I tried to describe the whole process here: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/wiki/Resource-pack-based-Texture-Config

In summary, this is a known issue and there won't be a solution to the current state. BUT the new system will fix it.
