### ISSUE TITLE
Custom textures not generating json files.

### ISSUE THREAD

**Issue by gartia** [Hunternif/AntiqueAtlas#343]
I'm on the latest version for 1.16 i wanted to make a texture pack for this map with extra biomes, but there is no json as the wiki states. Manually adding biome_textures.json and texture_sets.json does not work either.

Am i missing something for the latest version

**Comment by tyra314** [comment]
Tbh. use the [new system](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/wiki/Resource-pack-based-Texture-Config), which isn't out yet in a released version, but will be soon. Once it's out, it will completely replace the old system, which may or may not be broken anyways.

**Comment by gartia** [comment]
Thanks for the fast reply! I'll look into it

**Comment by tyra314** [comment]
6.0.0 is out, and so is the new system. Closing this for now.
