### ISSUE TITLE
Cannot  join to LAN server

### ISSUE THREAD

**Issue by Mnigos** [Hunternif/AntiqueAtlas#348]
With this mod loaded i cannot join into someone's LAN serwer. Just got 'Internal server error'.

logs:
[message (4).txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/6386872/message.4.txt)

**Forge version information**
 - Minecraft: [e.g. 1.16.5]
 - Forge: [e.g. 35.1.04]
 - AntiqueAtlas: [e.g. 5.4.2-forge]

**Comment by tyra314** [comment]
Duplicate of #314
