### ISSUE TITLE
Game crashs.

### ISSUE THREAD

**Issue by Taknax** [Hunternif/AntiqueAtlas#358]
**Describe the bug**

**To Reproduce**
1. Go to 'Inventory'
2. Click on 'anything'

**Expected behavior**
If i open inventory my game crashs.

**Screenshots**

**Forge version information (please complete the following information):**
 - Minecraft: [1.16.5]
 - Forge: [36.1.25]
 - AntiqueAtlas: [5.4.4-forge]

**Fabric version information (please complete the following information):**
 - Minecraft: []
 - Fabric Launcher: []
 - Fabric API: []
 - AntiqueAtlas: []

**Additional context**
Crashlog
https://pastebin.com/gVp5wmX7

**Comment by tyra314** [comment]
Duplicate of #314
