### ISSUE TITLE
Crash on world load with Project Brazier

### ISSUE THREAD

**Issue by enduum** [Hunternif/AntiqueAtlas#361]
When Project Brazier is enabled alongside Antique Atlas the game loads to the main menu and world selection perfectly fine, however joining a world produces a crash. Project Brazier or Antique Atlas alone does not produce a crash, Antique Atlas + Marg does not crash, it only appears to be Project Brazier and Antique Atlas that don't get along. Creating a new world also crashes.

To reproduce:
1. Install Antique Atlas, Marg, and Project Brazier
2. Launch game
3. Try to join a world
4. Crash. You may have seen a brief glimpse of your world before the game closed.

[crash report](https://pastebin.com/4YYXTqqs)
[latest.log](https://pastebin.com/aWMKsHzk)

Minecraft: 1.16.5
Forge: 36.1.32
Antique Atlas: 5.4.4
Project Brazier: 0.5.2.4
Marg: 0.6
Tested on a clean install with no other mods.

**Comment by tyra314** [comment]
dusplicate of #314
