### ISSUE TITLE
Server Warnings of "Worker-Main-xxx died" in console and freezing when saving world.

### ISSUE THREAD

**Issue by darthvader45** [Hunternif/AntiqueAtlas#366]
**Describe the bug**

**To Reproduce**
1. Go to a world
2. Load a bunch of chunks.
3. Notice chunks stop rendering at some point.
4. Save, go into the console and see "Worker_Main_xxx died" multiple times along with a ResourceLocationException

**Expected behavior**
Save, end up at main menu as usual.

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.0
 - AntiqueAtlas: 5.4.4-forge

Log: https://paste.ee/p/Fm2oy

**Comment by tyra314** [comment]
I believe this was fixed along the way to 6.2.0
