### ISSUE TITLE
Village markers appearing where no village exists + village markers are unremovable

### ISSUE THREAD

**Issue by KaiserYoshi** [Hunternif/AntiqueAtlas#37]
See attached screenshot of a zoomed-in map, showing a village marker and well tile at about where I'm standing, but as can be seen in the background, no village exists here.

Loading the world save in AMIDST also shows a village marker in this spot. AMIDST warns that villages may not generate in all marked locations due to obstructions (possibly this one failed because of the lake). Some sort of check to see if a village successfully generated, before placing the marker, may be in order.

EDIT: If it helps, the seed of this world is 7526775279340133531, and the coordinates of the not-village are X: +64, Z: -240.

Additionally, automatically-placed village markers (erroneous or not) cannot be removed with the delete tool.

![2015-02-14_16 07 55](https://cloud.githubusercontent.com/assets/9879642/6207981/698881ba-b56d-11e4-8852-3153ba412c86.jpg)

**Comment by Hunternif** [comment]
Thank you for the report. The non-existent village glitch happened to me as well and I had no idea what the cause of it was. The coordinates you provided will be a great help in fixing this.

As for not being able to delete the markers, it was made so deliberately, although in retrospect I'm not sure if it was such a good idea. Changing them so they can be removed may require significant changes in the core algorithms, but I'll see what I can do.
