### ISSUE TITLE
Got 1.17 Working

### ISSUE THREAD

**Issue by 109isaque10** [Hunternif/AntiqueAtlas#370]
I cannot push anything, so grab my zip of source code. With working jars inside it. It was tested before on a fabric game.
I just change build.gradle and gradle.properties. Nothing more.
[Download Source Code](https://www.mediafire.com/file/irvqb9tk8b5w9tm/AntiqueAtlas-1.17-fabric.zip/file)

**Comment by tyra314** [comment]
> I just change build.gradle and gradle.properties. Nothing more.

That's not nearly enough. Check out the 1.17-fabric branch instead. It has a lot of changes and some mixins are still broken.
