### ISSUE TITLE
Shader Bugs

### ISSUE THREAD

**Issue by ghost** [Hunternif/AntiqueAtlas#372]
1) I can move water with mouse movement.
2) The image on the atlas becomes blurry when you move the mouse.
3) After re-entering the world, unloaded chunks turn into this: (3 screen).

 - Minecraft: 1.16.5
 - Forge: 36.1.65
 - AntiqueAtlas: 6.0.0
 - Shader: Sildur's 1.29 Extreme-VL

![image](https://user-images.githubusercontent.com/75881942/126719282-140c22bc-15e4-4a6b-a783-51845bf3e5ed.png)
![image](https://user-images.githubusercontent.com/75881942/126719356-6e4fee00-2d96-4bbe-92cf-6a4b52b3f645.png)
![image](https://user-images.githubusercontent.com/75881942/126719969-bc30919c-d2d0-46a6-9859-c5d7beebab27.png)

**Comment by huine** [comment]
The same is happening with me.

- Minecraft: 1.16.5
- Forge: 36.1.65
- AntiqueAtlas: 6.0.0
- ComplementaryShaders_v4.1
