### ISSUE TITLE
Crashes with DynMus and Music Duration Reducer

### ISSUE THREAD

**Issue by evanbones** [Hunternif/AntiqueAtlas#373]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 23/07/21 10:50 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.audio.BackgroundMusicSelector.handler$bbc000$musicDr_getMaxDelay(SourceFile:531) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:musicdr.mixins.json:MusicMixin,pl:mixin:A}
	at net.minecraft.client.audio.BackgroundMusicSelector.func_232666_c_(SourceFile:35) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:musicdr.mixins.json:MusicMixin,pl:mixin:A}
	at net.minecraft.client.audio.MusicTicker.func_73660_a(SourceFile:41) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:MusicTickerMixin,pl:mixin:APP:charm.mixins.json:MusicTickerMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1490) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dynmus.json:MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dynmus.json:MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dynmus.json:MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.65.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_292, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 3397287760 bytes (3239 MB) / 4187619328 bytes (3993 MB) up to 4187619328 bytes (3993 MB)
	CPUs: 12
	JVM Flags: 22 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms4096m -Xss4M -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSConcurrentMTEnabled -XX:ParallelGCThreads=8 -XX:+UnlockExperimentalVMOptions -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -XX:+UseFastAccessorMethods -XX:CMSInitiatingOccupancyFraction=75 -XX:+CMSScavengeBeforeRemark -XX:+UseCMSInitiatingOccupancyOnly
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.65.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.65
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		infernal-expansion-2.0.0-beta.7.jar               |Infernal Expansion            |infernalexp                   |2.0.0-beta.7        |NONE      |Manifest: NOSIGNATURE
		TRansliterationLib-1.0.4.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.4               |NONE      |Manifest: NOSIGNATURE
		BetterF3-1.1.3-forge-1.16.5.jar                   |BetterF3 Forge                |betterf3forge                 |1.1.3               |NONE      |Manifest: NOSIGNATURE
		fish_in_planks-1.16.5-0.4.jar                     |Fish in Planks                |fish_in_planks                |1.16.5-0.4          |NONE      |Manifest: NOSIGNATURE
		glazedsymmetry-1.0.jar                            |Glazed Symmetry               |glazedsymmetry                |1.0                 |NONE      |Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |NONE      |Manifest: NOSIGNATURE
		farsight-1.2.1-1.16.5.jar                         |Farsight                      |farsight_spyglasses           |1.2.1-1.16.5        |NONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |NONE      |Manifest: NOSIGNATURE
		Controlling-7.0.0.23.jar                          |Controlling                   |controlling                   |7.0.0.23            |NONE      |Manifest: NOSIGNATURE
		Placebo-1.16.4-4.5.0.jar                          |Placebo                       |placebo                       |4.5.0               |NONE      |Manifest: NOSIGNATURE
		citadel-1.7.2-1.16.5.jar                          |Citadel                       |citadel                       |1.7.2               |NONE      |Manifest: NOSIGNATURE
		alexsmobs-1.11.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.11.1              |NONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-11.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-11     |NONE      |Manifest: NOSIGNATURE
		Bookshelf-1.16.5-10.1.11.jar                      |Bookshelf                     |bookshelf                     |10.1.11             |NONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		itemzoom-1.16.x-2.2.1.jar                         |Item Zoom Rekindled           |itemzoom                      |2.2.1               |NONE      |Manifest: NOSIGNATURE
		forgery-1.3.4.jar                                 |Fabrication                   |fabrication                   |1.3.4               |NONE      |Manifest: NOSIGNATURE
		SnowRealMagic-1.16.4-2.5.8.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.5.8               |NONE      |Manifest: NOSIGNATURE
		FpsReducer-mc1.16.5-1.20.jar                      |FPS Reducer                   |fpsreducer                    |mc1.16.5-1.20       |NONE      |Manifest: NOSIGNATURE
		dynmus-1.3.1.jar                                  |Dynamic Music                 |dynmus                        |1.3.1               |NONE      |Manifest: NOSIGNATURE
		Paraglider-1.16.5-1.3.1.1.jar                     |Paraglider                    |paraglider                    |1.3.1.1             |NONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.14.5.jar                 |Supplementaries               |supplementaries               |1.16.5-0.14.0       |NONE      |Manifest: NOSIGNATURE
		konkrete_1.1.6_MC_1.16.2-1.16.5.jar               |Konkrete                      |konkrete                      |1.1.6               |NONE      |Manifest: NOSIGNATURE
		bettererend-1.16.5-1.0.1.jar                      |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |NONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |NONE      |Manifest: NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |NONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.5.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.5        |NONE      |Manifest: NOSIGNATURE
		cleancut-mc1.16-2.2-forge.jar                     |Clean Cut                     |cleancut                      |2.2                 |NONE      |Manifest: NOSIGNATURE
		customizableelytra-1.16.4-1.5.4.jar               |Customizable Elytra           |customizableelytra            |1.16.4-1.5.4        |NONE      |Manifest: NOSIGNATURE
		repurposed_structures-1.16.5-2.7.12-forge.jar     |Repurposed Structures         |repurposed_structures         |1.16.5-2.7.12-forge |NONE      |Manifest: NOSIGNATURE
		musicdr-forge-1.2.0.jar                           |Music Duration Reducer        |musicdr                       |NONE                |NONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |NONE      |Manifest: NOSIGNATURE
		skinned_lanterns-1.16.5-1.3.1.jar                 |Skinned Lanterns              |skinnedlanterns               |1.16.5-1.3.1        |NONE      |Manifest: NOSIGNATURE
		shulker_enchantments-1.1.1.jar                    |Shulker Enchantments          |shulker_enchantments          |1.1.1               |NONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.jar                  |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2          |NONE      |Manifest: NOSIGNATURE
		antiquewaystones-1.2.jar                          |Antique Waystones             |antiquewaystones              |1.2                 |NONE      |Manifest: NOSIGNATURE
		sapience-1.16.5-1.1.2.jar                         |Sapience                      |sapience                      |1.1.2               |NONE      |Manifest: NOSIGNATURE
		architectury-1.20.28-forge.jar                    |Architectury                  |architectury                  |1.20.28             |NONE      |Manifest: NOSIGNATURE
		Chimes-1.16.5-0.9.5.jar                           |Chimes                        |chimes                        |0.9.5               |NONE      |Manifest: NOSIGNATURE
		cherishedworlds-forge-1.16.5-5.1.1.0.jar          |Cherished Worlds              |cherishedworlds               |1.16.5-5.1.1.0      |NONE      |Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |NONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |NONE      |Manifest: NOSIGNATURE
		BetterAdvancements-1.16.5-0.1.0.108.jar           |Better Advancements           |betteradvancements            |0.1.0.108           |NONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |NONE      |Manifest: NOSIGNATURE
		Kiwi-1.16.5-3.5.2.jar                             |Kiwi                          |kiwi                          |3.5.2               |NONE      |Manifest: NOSIGNATURE
		BetterGameMenu-1.16.5-1.0.jar                     |Better Game Menu              |bettergamemenu                |1.0                 |NONE      |Manifest: NOSIGNATURE
		BetterAnimationsCollection-v1.2b5-1.16.5.jar      |Better Animations Collection  |betteranimationscollection    |1.2b5               |NONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Notes-1.16.5-1.2.3.jar                            |Notes                         |notes                         |1.16.5-1.2.3        |NONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.111.jar                          |Just Enough Items             |jei                           |7.7.1.111           |NONE      |Manifest: NOSIGNATURE
		VisualWorkbench-v1.0.3-1.16.5.jar                 |Visual Workbench              |visualworkbench               |1.0.3               |NONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |NONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.2.0.jar                   |Abnormals Core                |abnormals_core                |3.2.0               |NONE      |Manifest: NOSIGNATURE
		environmental-1.16.5-1.0.0.jar                    |Environmental                 |environmental                 |1.0.0               |NONE      |Manifest: NOSIGNATURE
		allurement-1.16.5-1.2.0.jar                       |Allurement                    |allurement                    |1.2.0               |NONE      |Manifest: NOSIGNATURE
		peculiars-1.16.5-2.0.0.jar                        |Peculiars                     |peculiars                     |1.16.5-2.0.0        |NONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.16.5-3.0.1.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.1               |NONE      |Manifest: NOSIGNATURE
		berry_good-1.16.5-4.1.1.jar                       |Berry Good                    |berry_good                    |4.1.1               |NONE      |Manifest: NOSIGNATURE
		Enhanced-Mushrooms-1.16.5-3.0.9.jar               |Enhanced Mushrooms            |enhanced_mushrooms            |1.16.5-3.0.9        |NONE      |Manifest: NOSIGNATURE
		Bayou-Blues-1.16.5-1.0.5.jar                      |Bayou Blues                   |bayou_blues                   |1.16.5-1.0.5        |NONE      |Manifest: NOSIGNATURE
		differentiate-1.16.5-0.5.3.jar                    |Differentiate                 |differentiate                 |0.5.3               |NONE      |Manifest: NOSIGNATURE
		cookielicious-1.16.5-1.4.0.jar                    |Cookielicious                 |cookielicious                 |1.4.0               |NONE      |Manifest: NOSIGNATURE
		Better-Badlands-1.16.5-2.0.3.jar                  |Better Badlands               |better_badlands               |1.16.5-2.0.3        |NONE      |Manifest: NOSIGNATURE
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |NONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |NONE      |Manifest: NOSIGNATURE
		configured-1.1.0-1.16.5.jar                       |Configured                    |configured                    |1.1.0               |NONE      |Manifest: NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |NONE      |Manifest: NOSIGNATURE
		decorative_blocks_abnormals-1.2.jar               |Decorative Blocks Abnormals   |decorative_blocks_abnormals   |1.2                 |NONE      |Manifest: NOSIGNATURE
		decorative_winter-0.1.2.jar                       |Decorative Winter             |decorative_winter             |0.1.2               |NONE      |Manifest: NOSIGNATURE
		lazydfu-0.1.3.jar                                 |LazyDFU                       |lazydfu                       |0.1.3               |NONE      |Manifest: NOSIGNATURE
		bedspreads-forge-1.16.5-5.1.0.2.jar               |Bedspreads                    |bedspreads                    |1.16.5-5.1.0.2      |NONE      |Manifest: NOSIGNATURE
		farsight-1.5.jar                                  |Farsight mod                  |farsight_view                 |1.5                 |NONE      |Manifest: NOSIGNATURE
		catalogue-1.2.1-1.16.5.jar                        |Catalogue                     |catalogue                     |1.2.1               |NONE      |Manifest: NOSIGNATURE
		blockswap-1.1.1.jar                               |Block Swap                    |blockswap                     |1.1.1               |NONE      |Manifest: NOSIGNATURE
		voyage-1.16.4-1.0.3.jar                           |Voyage                        |voyage                        |1.0.3               |NONE      |Manifest: NOSIGNATURE
		Toast-Control-1.16.4-4.3.1.jar                    |Toast Control                 |toastcontrol                  |4.3.1               |NONE      |Manifest: NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.34.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.34            |NONE      |Manifest: NOSIGNATURE
		sodium-forge-2.9.6+rev.d687f65.jar                |SodiumReforged                |sodium                        |2.9.6+rev.d687f65   |NONE      |Manifest: NOSIGNATURE
		SimplyImprovedTerrain-0.3.2-Forge.jar             |Simply Improved Terrain       |simplyimprovedterrain         |0.3.2-Forge         |NONE      |Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.355.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.355           |NONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.65-universal.jar                |Forge                         |forge                         |36.1.65             |NONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		seasonals-1.16.5-2.0.0.jar                        |Seasonals                     |seasonals                     |1.16.5-2.0.0        |NONE      |Manifest: NOSIGNATURE
		ConsoleExperience-v1.7.2-1.16.5.jar               |Console Experience            |consoleexperience             |1.7.2               |NONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		neapolitan-1.16.5-2.1.0.jar                       |Neapolitan                    |neapolitan                    |2.1.0               |NONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |NONE      |Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		selene-1.16.5-1.5.jar                             |Selene                        |selene                        |1.16.5-1.0          |NONE      |Manifest: NOSIGNATURE
		antiqueatlas-6.0.1-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.0.1-forge-mc1.16.5|NONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.65-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |NONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |NONE      |Manifest: NOSIGNATURE
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               |NONE      |Manifest: NOSIGNATURE
		ensorcellation-1.16.4-1.2.0.jar                   |Ensorcellation                |ensorcellation                |1.2.0               |NONE      |Manifest: NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |NONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.12.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.12              |NONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		ItemPhysicLite_v1.4.8_mc1.16.5.jar                |ItemPhysic Lite               |itemphysiclite                |1.4.0               |NONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |NONE      |Manifest: NOSIGNATURE
		Abundance-1.16.5-1.0.5.jar                        |Abundance                     |abundance                     |1.16.5-1.0.5        |NONE      |Manifest: NOSIGNATURE
		Jade-1.16.4-2.7.1.jar                             |Jade                          |jade                          |2.7.1               |NONE      |Manifest: NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |NONE      |Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |NONE      |Manifest: NOSIGNATURE
		CreateTweaker-1.0.0.14.jar                        |CreateTweaker                 |createtweaker                 |1.0.0.14            |NONE      |Manifest: NOSIGNATURE
		lepton-1.16.5-1.3.1.jar                           |Lepton                        |lepton                        |1.3.1               |NONE      |Manifest: NOSIGNATURE
		farmersdelightintegration-1.16.5-1.0.3.jar        |Farmer's Delight Integration  |farmersdelightintegration     |1.16.5-1.0.3        |NONE      |Manifest: NOSIGNATURE
		personality-1.16.5-1.0.2.jar                      |Personality                   |personality                   |1.0.2               |NONE      |Manifest: NOSIGNATURE
		atmospheric-1.16.5-3.1.0.jar                      |Atmospheric                   |atmospheric                   |3.1.0               |NONE      |Manifest: NOSIGNATURE
		notenoughanimations-1.2.4.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.2.4               |NONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.1.1.jar                           |Flywheel                      |flywheel                      |1.16-0.1.1          |NONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2b.jar                       |Create                        |create                        |v0.3.2b for 1.16.5  |NONE      |Manifest: NOSIGNATURE
		savageandravage-1.16.5-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |NONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.115.jar                         |Mantle                        |mantle                        |1.6.115             |NONE      |Manifest: NOSIGNATURE
		Inspirations-1.16.5-1.2.3.37.jar                  |Inspirations                  |inspirations                  |1.2.3.37            |NONE      |Manifest: NOSIGNATURE
		cookiecore-1.16.2-3.0.2-9389769.jar               |CookieCore                    |cookiecore                    |1.16.2-3.0.2-9389769|NONE      |Manifest: NOSIGNATURE
		magicfeather-1.16.2-3.2.0.jar                     |Magic Feather                 |magicfeather                  |1.16.2-3.2.0        |NONE      |Manifest: NOSIGNATURE
		diet-forge-1.16.5-0.36.jar                        |Diet                          |diet                          |1.16.5-0.36         |NONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.16.4-4.5.1.jar                    |FastWorkbench                 |fastbench                     |4.5.1               |NONE      |Manifest: NOSIGNATURE
		autumnity-1.16.5-2.1.1.jar                        |Autumnity                     |autumnity                     |2.1.1               |NONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |NONE      |Manifest: NOSIGNATURE
		Quark-r2.4-316.jar                                |Quark                         |quark                         |r2.4-316            |NONE      |Manifest: NOSIGNATURE
		charm-forge-1.16.5-2.3.2.jar                      |Charm                         |charm                         |2.3.2               |NONE      |Manifest: NOSIGNATURE
		charmonium-forge-1.16.5-2.3.2.jar                 |Charmonium                    |charmonium                    |2.3.2               |NONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.16.5-1.1.1.jar                |Abnormals Delight             |abnormals_delight             |1.1.1               |NONE      |Manifest: NOSIGNATURE
		DiagonalFences-v1.1.1-1.16.5.jar                  |Diagonal Fences               |diagonalfences                |1.1.1               |NONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		FastFurnace-1.16.4-4.4.0.jar                      |FastFurnace                   |fastfurnace                   |4.4.0               |NONE      |Manifest: NOSIGNATURE
		ferritecore-2.0.5-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.5               |NONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		PuzzlesLib-v1.0.10-1.16.5.jar                     |Puzzles Lib                   |puzzleslib                    |1.0.10              |NONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		mannequins-1.0.1-1.16.5-forge.jar                 |Mannequins                    |mannequins                    |1.0.1               |NONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.9.jar                         |Valhelsia Core                |valhelsia_core                |16.0.9              |NONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.4.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.4        |NONE      |Manifest: NOSIGNATURE
		OpenLoader-1.16.5-9.0.3.jar                       |OpenLoader                    |openloader                    |9.0.3               |NONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.11, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor

**Comment by tyra314** [comment]
I'm not even seeing AntiqueAtlas in the backtrace. Also, update AntiqueWaystones.

**Comment by evanbones** [comment]
It's weird, because it only happens when Antique Atlas is installed. I'll do some more testing and let you know what I find

**Comment by evanbones** [comment]
Bizarre, it doesn't happen when I update Antique Waystones. Still have no idea why that would happen. Sorry about that!
