### ISSUE TITLE
Unable to join server after updating AntiqueAtlas to latest ver

### ISSUE THREAD

**Issue by Alkiasan** [Hunternif/AntiqueAtlas#374]
**Describe the bug**
Whenever joining the server, the player is disconnected immediately.

**To Reproduce**
1. Install mod
2. Attempt to join server

**Expected behavior**
Player should be able to join just fine

**Screenshots**
![image](https://user-images.githubusercontent.com/62717881/126838248-92a6d63d-458a-4a76-8d47-c18d3c93c54f.png)

**Fabric version information (please complete the following information):**
 - Minecraft: [1.16.5]
 - Fabric Launcher: [0.11.6]
 - Fabric API: [0.35.1]
 - AntiqueAtlas: [6.0.0]

**Comment by Alkiasan** [comment]
Tried using XLPackets. Issue still persisted.

**Comment by Alkiasan** [comment]
An update to this, Pregenerating the nether with Chunky and antiqueAtlas installed seems to cause a huge (289kb) aAtlasTiles.dat (Attached). Deleting the file to reset it fixes the disconnect issue.
[aAtlasTiles.zip](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/6871131/aAtlasTiles.zip)

**Comment by tyra314** [comment]
During the pregeneration, a large number of nether fortresses are generated. AA tracked those and stored the matching tiles in the file you attached. The problem is that apparently the whole file is transmitted in one packet during login. I guess I need to split that into several packets.
