### ISSUE TITLE
crash when opening a blank atlas 1.17

### ISSUE THREAD

**Issue by kuroyure** [Hunternif/AntiqueAtlas#375]
https://pastebin.com/S2a2wQvB 
crash report, im using the latest version of everythng

**Comment by tyra314** [comment]
Please provide the log file as well

**Comment by kuroyure** [comment]
> Please provide the log file as well

https://pastebin.com/cvv4Ecur you got it cheif

**Comment by tyra314** [comment]
Do you have the new world gen enabled by any chance? In particular the lush cave or drip stone cave?

**Comment by kuroyure** [comment]
> Do you have the new world gen enabled by any chance? In particular the lush cave or drip stone cave?

yep, via some mods, i assume that screws the textures n stuff

**Comment by tyra314** [comment]
Yes. The auto-selection of textures doesn't work for the new biomes and I borked up the graceful fallback. Until a bug fix, you could just use a resource pack defining the textures though. Try the attached one.
[aa-caves.zip](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/6911394/aa-caves.zip)

**Comment by tyra314** [comment]
I think i fixed this long time ago.
