### ISSUE TITLE
Adding to the Wiki

### ISSUE THREAD

**Issue by gh0stf1sh** [Hunternif/AntiqueAtlas#377]
I did some digging first and I found a solution to my problems with adding custom textures buried in previous issues but some may find it helpful if the link below that people have been redirected to was put into the wiki.

https://github.com/AntiqueAtlasTeam/AntiqueAtlas/wiki/Resource-pack-based-Texture-Config

oh also this might be a helpful link to put in there too?
https://www.rpgmakerweb.com/blog/classic-tutorial-making-an-autotile

**Comment by tyra314** [comment]
done
