### ISSUE TITLE
Biome textures render bug

### ISSUE THREAD

**Issue by MadeshaD** [Hunternif/AntiqueAtlas#378]
**Describe the bug**
The textures of biomes are not rendered when the CaveBiomeAPI 1.3.1 is installed.

**Screenshots**
![2021-08-07_22 07 49](https://user-images.githubusercontent.com/65042032/128608867-87d5e71d-71c0-4915-aa80-8aca07fe0bb0.png)

**Forge version information:**
 - Minecraft: 1.16.5
 - Forge: 36.2.2
 - AntiqueAtlas: 6.0.1
 - CaveBiomeAPI: 1.3.1

**Additional context**
There was no such problem with the CaveBiomes 2.0.

**Comment by valkohaus** [comment]
The bug is still present, has the changes been made to the actual mod file? I don't really understand Java...
