### ISSUE TITLE
Blurry map with shaders when moving.

### ISSUE THREAD

**Issue by maddoodles** [Hunternif/AntiqueAtlas#380]
**Describe the bug**
The map is blurry when moving and using shaders, currently tried with Sildur's Shaders

**To Reproduce**
1. Load a map and start moving, whether on the main hotbar or in the off-hand, it will be blurry when moving at all. Clicking to use the map is fine however.

**Screenshots**
[Screenshot](https://i.imgur.com/1Dd12Bf.png)

**Fabric version information (please complete the following information):**
 - Minecraft: [1.16.5]
 - Fabric Launcher: [0.11.6]
 - AntiqueAtlas: [6.0.0-fabric]

**Comment by tyra314** [comment]
What are you using to run the shaders? Iris? It works fine for me, with Sildurs v.129 Extreme, Iris 1.1.1 with the integrated Sodium v0.2.0+IRIS3-build.49

**Comment by tyra314** [comment]
On a second thought. Judging from the broken textures, you're using OptiFine. 😢 It's always the same with Optifine (┛ಠ_ಠ)┛彡┻━┻

**Comment by maddoodles** [comment]
Oh shoot, I forgot that bit of info sorry. Yeah I'm using Optifine, between that and Sodium Optifine breaks Campanion the least. '^^

**Comment by tyra314** [comment]
I can't do anything about Optifine being Optifine. Though, there has been some fixes up to 6.2.0. Try if that works. I'm closing it anyways.
