### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by TooManyKitKats** [Hunternif/AntiqueAtlas#381]
I do love the direction you have taken with the held map as it is beautiful, but would you consider making an addon that re adds the minimap version? I wish I could use the held book but with the shader [Nostalgia](https://www.curseforge.com/minecraft/customization/nostalgia-shader) there are too many visual issues for it to be usuable. I completly get saying no and I thank you for mantaining this wonderful mod. Also I apologize for the format but I did not see a template for filing an issue or complaint.

**Comment by tyra314** [comment]
The minimap won't come back from me. I'd rather fix the blur. See #380
