### ISSUE TITLE
AntiqueAtlas has zero detail

### ISSUE THREAD

**Issue by zndrmn** [Hunternif/AntiqueAtlas#385]
The AntiqueAtlas only show where lakes / rivers are
Im like 60% sure its a mod conflict 

1. open a Atlas
2. observe 

Should show tree and biome types

https://i.imgur.com/iuDVtt0.png

 - Minecraft: [1.16.4]
 - Forge: [36.2.0]
 - AntiqueAtlas: [6.0.1-forge]

Could be a mod conflict, also using a modpack called [Extreme Survival Modpack](https://www.curseforge.com/minecraft/modpacks/extreme-survival-modpack). It occurs on versions 4.7.7:A and 4.6.7:A worked fine on 3.6.7:A

**Comment by tyra314** [comment]
Duplicate of #378
