### ISSUE TITLE
When holding an atlas in each hand both hands render the main-hand atlas

### ISSUE THREAD

**Issue by bwanders** [Hunternif/AntiqueAtlas#389]
**Describe the bug**
When holding an atlas and the off-hand, and another one in the main hand both atlases render the information from the one in the main hand.

**To Reproduce**
1. Take two empty atlases
2. Open the first one, and walk around a bit to fill it out
3. Open the second one, and add a marker on it
4. Put one of them in off-hand, the other in main hand
5. See both atlases display the same thing, check marker just added in only one appear on both or neither. (You can even swap them with `f` and see both display the other atlases' info)

**Expected behavior**
Both atlases display their own information.

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.0
 - AntiqueAtlas: 6.0.1-forge

**Comment by tyra314** [comment]
I think I fixed that.
