### ISSUE TITLE
[incompatibility] with inventorio

### ISSUE THREAD

**Issue by SylisMC** [Hunternif/AntiqueAtlas#390]
**Describe the bug**
Map doesnt update in offhand with [inventorio](https://www.curseforge.com/minecraft/mc-mods/inventorio)

**Fabric version information (please complete the following information):**
 - Minecraft: 1.17.1
 - fabric-api-0.39.2+1.17.jar
 - antiqueatlas-6.0.0-fabric-mc1.17.1.jar
 - inventorio-1.17-fabric-1.6.2.jar

**Comment by tyra314** [comment]
Does it work in other slots?

**Comment by SylisMC** [comment]
No, it doesnt work with any of the "extra" slots added by inventorio.

the offhand by default has 4 "slots" that you can scroll through and none of them trigger the map being updated
with the "deep pockets" enchant provided by the mod, you can upgrade your inventory by 9 slots (up to 27) and your offhand from 4 to 8 slots, none of the extra slots work. but the offhand is by default replaced with the 4 slotted offhand

**Comment by tyra314** [comment]
I think this is a problem in Inventorio. They need to properly `inventoryTick()` the items in their inventory slots.
