### ISSUE TITLE
Antique Atlas Graphical Bug

### ISSUE THREAD

**Issue by Phoebius96** [Hunternif/AntiqueAtlas#393]
**Describe the bug**
A weird graphical bug appeared in the atlas out of the blue. I did not change anything about my modpack, so it just happened from one day to another.

I have no biome or worldgen mods installed.

![2021-09-01_17 37 59](https://user-images.githubusercontent.com/89929296/131702330-7a68ba1d-0ccd-462f-9eb8-66df0315047d.png)

**Fabric version information (please complete the following information):**
 - Minecraft: 1.17.1
 - Fabric Launcher: 0.11.6
 - Fabric API: 0.39.2
 - AntiqueAtlas: 6.0.0

**Comment by tyra314** [comment]
OptiFine does OptiFine things. 

Please update, that issue was fixed in the latest release.
