### ISSUE TITLE
Suggestion: Limit the initial area of the map, are more map pages to increase size

### ISSUE THREAD

**Issue by winsrp** [Hunternif/AntiqueAtlas#395]
So, when the atlas is initially created you get a 16x16 area around you of map (just to say a number it can be configurable), and if you explore further the map won't get updated.

If you combine your atlas and surround it with empy maps in a crafting table, you increase the area of you map, and move to 32x32.

Do the same process again and you get 48x48, then 64x64, you get the idea.

This way we can use the normal minecraft maps for something along this mod. (but it can be just normal paper if you like that better)

**Comment by tyra314** [comment]
Thank you for your suggestion. I have thought about it for a while, but I don't see it fitting into my vision of the mod.

There's also the related idea to consume inc sacks, which I like more, as it's a bit more targeted. (See #216)
