### ISSUE TITLE
Atlas Minimap does not work

### ISSUE THREAD

**Issue by LordPigger** [Hunternif/AntiqueAtlas#405]
**Describe the bug**
Atlas minimap does not work when enabled in config

**Expected behavior**
I have the config set up to when it is in my hotbar, the minimap appears. 

**Version information (please complete the following information):**
 - AntiqueAtlas: 6.0.1
 - Minecraft: 1.16.5
 - Forge: 36.2.8
 
**Additional context**
![image](https://user-images.githubusercontent.com/93689129/140237550-b7b65cfc-b0ef-49a8-a382-fc44492a42e3.png)
here is how it is set up in the client config

**Comment by baltassarmonkey** [comment]
As of version 6, the minimap has been removed, although the config option seems to sometimes remain. The preferred way to use it is like vanilla maps, hold it in your offhand or main hand. Although personally I would like the previous minimap as an option.

**Comment by tyra314** [comment]
Yeah, the option should be removed. Put the atlas in your offhand slot.

**Comment by tyra314** [comment]
I have one question though, did you update from a 5.x release of AA, or did you start fresh?

**Comment by baltassarmonkey** [comment]
I am currently playing a mod pack which came bundled with the config. Which would be why the config option is still in the file.

**Comment by LordPigger** [comment]
I deleted the config and replaced with a fresh config to make sure it wasnt still an issue. the mini map options just appears at the bottom of the config list

**Comment by tyra314** [comment]
Fixed in 6.2.0
