### ISSUE TITLE
Doesn't work together with meteor-client mod on fabric

### ISSUE THREAD

**Issue by n-chicken** [Hunternif/AntiqueAtlas#407]
**Describe the bug**
Screen turns blank when trying to load just two mods, [meteor-client](https://github.com/MeteorDevelopment/meteor-client/) and AntiqueAtlas.

**To Reproduce**
Download both and try to run

**Expected behavior**
They work together and no bugs or integration difficulties ever happen anywhere in the world

**Version information (please complete the following information):**
 - AntiqueAtlas: 6.1.1
 - Minecraft: 1.17.1
 - Fabric API: 0.11.6
 
Here's [the logs](http://ix.io/3F71)

**Comment by tyra314** [comment]
Works fine for me with the dev-build 0.4.7 - 1334. Please provide more details.

**Comment by tyra314** [comment]
I'm closing it, as there won't be another update for 1.17 anyways.
