### ISSUE TITLE
Ive got a few questions if you have the time.

### ISSUE THREAD

**Issue by gravestristen** [Hunternif/AntiqueAtlas#41]
Do you mind explaining to me how exactly it maps and if it updates parts of the map if the area has been edited.

**Comment by Hunternif** [comment]
Hi!
The map is constructed primarily using biome IDs that are associated with every block (every X-Z coordinate pair) in a vanilla world. This means that if you edit an area by digging a hole or building a house, those changes won't be reflected in my map. In fact, I don't know of any in-game methods or mods that allow you to change the world's underlying biome ID information.
But there is a mechanism in AntiqueAtlas that allows other mods to modify the map via an API in any way they please by putting custom data on a layer on top of what is constructed from biome IDs. This method is used internally to map ponds of water and lava, as well as everything in the Nether. So in theory, if you make an artificial pond, it should appear on a map (but I haven't tested that, so if you please tell me if it works as expected).
I am planning to make an in-game map editor GUI for server OPs that makes use of this API, but as of now there isn't a way to really modify the map.

**Comment by gravestristen** [comment]
Ill test that next time I launch up minecraft, thank you, I was asking because I had noticed that I cleared all the trees from an area but they were still there on the map.

**Comment by gravestristen** [comment]
I tested it on a superflat world and yes it will recognize a body of water if it is over a certain amount.

**Comment by Hunternif** [comment]
Thanks a lot for confirming!

**Comment by gravestristen** [comment]
your welcome I dont mind it at all, if you ever need help just give me a call and ill be happy to!
