### ISSUE TITLE
Curse Lacks Dependency

### ISSUE THREAD

**Issue by Hexidecimark** [Hunternif/AntiqueAtlas#410]
**Describe the bug**
Because Cloth is not listed as a dependency, installing the mod via curse causes the game to refuse to start until it is installed. 

**To Reproduce**
1. Install AA 6.0.1 1.16.5 via curse
2. Attempt to start game without other mods installed

**Expected behavior**
Game starts

**Version information (please complete the following information):**
 - AntiqueAtlas: 6.0.1
 - Minecraft: 1.16.5
 - Forge: 36.2.4
 - Fabric Launcher: X
 - Fabric API: X

This may be fixed by simply telling curse that this mod requires cloth-config

**Comment by tyra314** [comment]
Should be fixed. Thanks.
