### ISSUE TITLE
Custom mod biomes resource pack fails to load texture sets

### ISSUE THREAD

**Issue by IAnon** [Hunternif/AntiqueAtlas#411]
**Describe the bug**
Custom resource pack that supports mod biomes fails to load texture sets because it cant find the specified texture and even crashes Minecraft or displays resource load failed. Only happens while the resource pack is zipped, works as intended when unzipped.

**To Reproduce**
1. Go to 'https://www.curseforge.com/minecraft/texture-packs/antiqueatlasems'
2. Download and install the resource pack.
3. Launch Minecraft
4. See errors in logs.

**Expected behavior**
Should load the texture sets and textures as any resource pack.

**Version information (please complete the following information):**
 - AntiqueAtlas: antiqueatlas-6.0.1-forge-mc1.16.5
 - Minecraft: 1.16.5
 - Forge: 36.2.2
 - Fabric Launcher: N/A
 - Fabric API: N/A
 
**Additional context**
Sometimes the textures get defaulted to an antiqueatlas folder texture while other times it uses the debug texture instead.
https://pastebin.com/Qni9pmKx for the general error that fails to load the texture set.
https://pastebin.com/rGUQi27d for the crash that happens, although the Description is not always the same.
Please see https://www.mediafire.com/file/jqwj90iqwrijcuz/2021-11-15-1.log.gz/file for general log showing the all of the errors as seen above (text is too large for pastebin).

**Comment by tyra314** [comment]
There is actually an error in the resource pack: 

> [20:04:28] [ForkJoinPool.commonPool-worker-23/WARN] (Antique Atlas) Failed to read textures!
 net.minecraft.util.InvalidIdentifierException: Non [a-z0-9/._-] character in path of location: antiqueatlas:textures/gui/tiles/dense_forest2UNUSED.png

This is the problem, as it prevents a random amount of textures from being loaded. I need to fix that, but until then, rename the texture, or delete it, if it is unused.

**Comment by tyra314** [comment]
And with fixing I mean, adding a more obvious error message.

**Comment by IAnon** [comment]
Damn, I looked through the log so many times and never saw this before. If I saw it it would have at least gave me a hint as to what the problem was. Thanks for the quick reply.

I removed the textures and it works now.

**Comment by tyra314** [comment]
I think this should be fixed in 6.2.0, 7.0.0, and the resource pack fixed it also.
