### ISSUE TITLE
Death marker label format error

### ISSUE THREAD

**Issue by ghost** [Hunternif/AntiqueAtlas#415]
**Describe the bug**
1.12.2. When killed, map STILL says "format error: here lies [playername]".

**To Reproduce**
1.  Die with opened Atlas
2. Check the same Atlas Number for your death location, see text "Format error":

![image](https://user-images.githubusercontent.com/71896090/146063486-f61fb893-eeb6-4b02-8e58-fc864c62f2fb.png)

**Version information (please complete the following information):**
 - AntiqueAtlas: Latest 1.12.2
 - Minecraft: 1.12.2

**Comment by tyra314** [comment]
There won't be another 1.12 update, so I'm closing this.
