### ISSUE TITLE
Crashes upon launching (incompatible Cloth Config API version)

### ISSUE THREAD

**Issue by nlizmi** [Hunternif/AntiqueAtlas#418]
**Describe the bug**
Upon trying to launch the game with Antique Atlas installed, the game crashes, and Fabric Loader provides the crash report shown below.

**To Reproduce**
1. Using the CurseForge Launcher, install Antique Atlas 6.1.0 with Cloth Config API 4.13.49 on Minecraft 1.16.5, Fabric Launcher 0.12.12
2. Attempt to launch the game

**Expected behavior**
The game is expected to launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/42084530/149638211-a60d95c7-40fd-4657-aa3e-e79994467e0e.png)
![image](https://user-images.githubusercontent.com/42084530/149638241-36bcbff8-7f8c-4d4f-8232-51890d3e73e6.png)

**Fabric version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Fabric Launcher: 0.12.12
 - Fabric API: 0.42.0
 - AntiqueAtlas: 6.1.0

**Additional context**
I have followed the suggested solution of downgrading the Cloth Config API version to 4.11.26, however this causes a bunch of issues with other mods I have installed (namely REI and Goblin Trader), and I would prefer to keep all of the mods installed.

**Comment by tyra314** [comment]
fixed in 16786ee394218d9d13e8a24964bcb2783ed84bd4
