### ISSUE TITLE
Crash game when using M key to open map

### ISSUE THREAD

**Issue by Stadde1n** [Hunternif/AntiqueAtlas#425]
**Describe the bug**
When i use map on "m" i have crash game, just opens an empty map and crashes
but when I use the book everything is fine

**To Reproduce**

**Expected behavior**
working map on keybind
**Screenshots**
https://user-images.githubusercontent.com/104253546/164888499-4bdc2a52-39fa-4469-971c-d392997211ac.png

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.29
 - AntiqueAtlas: 5.4.4

**Additional context**
[crash-2022-04-23_12.20.28-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/8546595/crash-2022-04-23_12.20.28-client.txt)

**Comment by tyra314** [comment]
I wasn't able to reproduce this with 6.2.0 and 7.0.0 so I'm closing it.
