### ISSUE TITLE
/give command for old atlas?

### ISSUE THREAD

**Issue by MeowingInsanely** [Hunternif/AntiqueAtlas#430]
Lost an atlas due to a bug, how to /give it back?

**Comment by tyra314** [comment]
For newer version of Minecraft (since 1.13) use:

`/give @p antiqueatlas:antique_atlas{atlasID:XXX}`

and replace the `XXX` with the ID of the lost atlas.

For older versions of Minecraft use:

`/give @p antiqueatlas:antique_atlas 1 XXX` 

and replace the `XXX` with the ID of the lost atlas.
