### ISSUE TITLE
Payload Error on mod version 6.0.1-forge in MC 1.16.5

### ISSUE THREAD

**Issue by DarkeFae** [Hunternif/AntiqueAtlas#431]
**Describe the bug**
Payload error Same as #103 but with mod version: antiqueatlas-6.0.1-forge-mc1.16.5.jar

**To Reproduce**
it seems to be a very random issue that is not consistently replaceable. 
It sometimes affects one player but not another, but later who is affected with change.

**Expected behavior**
Join the server and be able to play.

**Screenshots**
![aa error](https://user-images.githubusercontent.com/109184801/179116498-f394de0a-6029-470b-ba16-99405a6e8546.png)

**Forge version information (please complete the following information):**
 - Minecraft:1.16.5
 - Forge: 1.16.5-36.2.34 Forge Version
 - AntiqueAtlas: 6.0.1-forge

**Comment by tyra314** [comment]
This should be fixed in 6.2.0 and 7.0.0
