### ISSUE TITLE
Antique Atlas displays placeholder/missing textures with Biomes O' Plenty

### ISSUE THREAD

**Issue by ChrisClickbait** [Hunternif/AntiqueAtlas#433]
Antique Atlas displays placeholder/missing textures with Biomes O' Plenty

When loading up a world and opening an Antique Atlas in modded biomes a placeholder/ missing texture shows representing the modded biomes.

**To Reproduce**
1. Download Biomes O' Plenty with Antique Atlas and required libraries.
2. Create a new world.
3. Open Antique Atlas on or near a Biomes O' Plenty biome.
4. See placeholder/error textures. 

Expected behavior would be the normal icons and textures showing up for Biomes O' Plenty biomes.

**Screenshots**
![Screenshot_6](https://user-images.githubusercontent.com/5308590/189578483-8125fd8c-7b16-4479-89ab-14c8cfd1cfdf.png)
![Screenshot_12](https://user-images.githubusercontent.com/5308590/189578503-84a64aa9-a594-4729-bcbd-9ce4e0ed308f.png)

**Forge version information (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.1.45
 - AntiqueAtlas: 7.0.0-forge-mc1.18.2
 - Architectury 4.9.84
 - Biomes O' Plenty 1.18.2-16.0.0.134
 - TerraBlender 1.2.0.126
 - Cloth Config 6.4.90
 
**Additional context**
Assuming this is also happening with other modded biomes, since this is just a brand new build. 
(Thanks for updating to 1.18.2!)

**Comment by CertifiedFish** [comment]
Same verison, this also happens with the vanilla sparse jungle biome. (minecraft:sparse_jungle)
