### ISSUE TITLE
[1.18.2] Terralith biomes render incorrectly

### ISSUE THREAD

**Issue by mont-40** [Hunternif/AntiqueAtlas#434]
**Describe the bug**
Terralith biomes render incorrectly with funky looking placeholder tiles.

**Screenshots**
![atlas](https://user-images.githubusercontent.com/4014599/189770151-a8a267d5-cf53-42b1-88c8-50e010ac0396.png)
The left biome is a terralith:lush_valley, the right one a terralith:blooming_valley. Several other Terralith biomes not in this screenshot render in the same way.

**Version information (please complete the following information):**
 - AntiqueAtlas: 7.0.0
 - Terralith: 2.2.1a
 - Minecraft: 1.18.2
 - Forge: 40.1.73

**Comment by tyra314** [comment]
Duplicate of #433

**Comment by tyra314** [comment]
Also, it's fixed in 7.0.1
