### ISSUE TITLE
mouseClicked event handler when clicking map markers [1.16.5]

### ISSUE THREAD

**Issue by Jesslerchip** [Hunternif/AntiqueAtlas#437]
**Describe the bug**
Basically what the title says. Clicking a map marker makes the game save and crash.

**To Reproduce**
1. Open the full view of the atlas.
2. Click on a marker.

**Version information (please complete the following information):**
 - AntiqueAtlas: 6.2.0
 - Minecraft: 1.16.5
 - Forge: 36.2.34
[crash-2022-09-14_15.34.50-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/9569832/crash-2022-09-14_15.34.50-client.txt)

**Comment by tyra314** [comment]
I think I already fixed that in 6.2.1
