### ISSUE TITLE
Dragging the map is sticky (not smooth) after updating to v6.2.1 for 1.16.5 

### ISSUE THREAD

**Issue by malinkody** [Hunternif/AntiqueAtlas#439]
**Describe the bug**
Dragging the map around after opening it on v6.2.1 feels like it lags behind or moves slower and then faster. It gives off a sticky feeling in comparison to v6.0.1.

**To Reproduce**
1. Open the atlas by right click while holding
2. Drag the map with the mouse pointer

**Expected behavior**
Smooth dragging of the map as it was in v6.0.1 for mc1.16.5

**Version information (please complete the following information):**
 - AntiqueAtlas: v6.2.1
 - Minecraft: v1.16.5
 - Forge: 36.2.39

**Comment by tyra314** [comment]
What's your screen resolution and GUI scale?

*edit: And do you use full-screen or window mode?

**Comment by tyra314** [comment]
Should be fine in 6.2.2 and 7.0.3

**Comment by malinkody** [comment]
Sorry for the late reply. I tested it with the newer version and it's incredibly fast and responsive now. Thank you.
