### ISSUE TITLE
Random Houses spawn in the map

### ISSUE THREAD

**Issue by INooBTooMuch** [Hunternif/AntiqueAtlas#443]
**Describe the bug**
When I open the atlas random houses are shown but I don't see any structures spawning. 

**Expected behavior**
The map to not show random structures that aren't there.

**Screenshots**
![2022-09-20_12 26 45](https://user-images.githubusercontent.com/107572028/191222186-17ae76dc-4114-4866-95cf-e5b53323f6d9.png)

**Version information (please complete the following information):**
 - AntiqueAtlas: 7.0.3
 - Minecraft: 1.18.2
 - Forge: 40.1.80
 
**Additional context**
These are my [Mods](https://gist.github.com/INooBTooMuch/10cfa142657308873bc94d017f336ec9#file-mods-in-testing-v_1_9)

**Comment by malinkody** [comment]
I've encountered this many times with other modded structures. Especially underground ones. I've had modded mineshafts appear as lines of churches on the map which was confusing at first since there was nothing on the surface.

**Comment by INooBTooMuch** [comment]
I tried Going underground but I didn't find anything, at least under this one in the picture.

**Comment by tyra314** [comment]
Can you try, if this build fixes the problem? Though, make sure to try it in a new world you don't care about, it might be buggy and messes things up even more :bug: 

https://github.com/AntiqueAtlasTeam/AntiqueAtlas/suites/10239038324/artifacts/502070174

**Comment by INooBTooMuch** [comment]
And where do I put it??
Like, is it in place of the mod, do I extract the forge file that is in the ziped...just give me some steps to do to test it

**Comment by tyra314** [comment]
extract the zip file. It contains the mod jar for forge and fabric down in folders.

**Comment by INooBTooMuch** [comment]
It doesn't seem to load any random things, but in case I did something wrong I only pasted the `antiqueatlas-7.0.3-forge-mc1.18.2.jar` in the mods folder because I was getting crashes in the minecraft launcher when I did the rest too.

**Comment by tyra314** [comment]
That sounds right. So it's fixed then? Thanks for testing.
