### ISSUE TITLE
Crashes on startup 1.18.2 (Forge)

### ISSUE THREAD

**Issue by LexaWB** [Hunternif/AntiqueAtlas#445]
Minecraft crashes on startup, does not open before error occurs (exit code 1)

**Comment by tyra314** [comment]
Please provide a crash log

**Comment by LexaWB** [comment]
there was no crash log available to copy

**Comment by tyra314** [comment]
Then add the architectury-api mod.

**Comment by tyra314** [comment]
Duplicate of #444
