### ISSUE TITLE
Map resetting after restarting game 

### ISSUE THREAD

**Issue by Cookyz1** [Hunternif/AntiqueAtlas#446]
**Describe the bug**
Every time I open the game the Atlas resets completely (waypoints included) 
I tried to 

**Version information (please complete the following information):**
 - AntiqueAtlas: 7.0.3
 - Minecraft: 1.18.2
 - Fabric Launcher: 0.14.9
 - Fabric API: 0.59.0
 
[Modlist.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/9692047/Modlist.txt)

**Comment by tyra314** [comment]
Does with happen on a server or in single-player?

**Comment by Cookyz1** [comment]
Single-player

**Comment by tyra314** [comment]
Please try the following:

1. Start Minecraft
2. Create a new world in single-player in creative
3. Give yourself a new atlas and open it
4. save the game
5. exit minecraft
6. save the logfile and upload it here

**Comment by Gotyam** [comment]
As I have been having the same issue, though on forge instead, I will at the very least provide mine now a month later than the issue being noted. Version 7.0.3 for forge 1.18.2 (40.1.84)
[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/9942735/latest.log)

**Comment by wingedseahorse** [comment]
Ditto for me on fabric. Further, the atlas seems to be unable to regenerate map in the lost area. 
![2022-11-11_15 07 37](https://user-images.githubusercontent.com/7261317/201261276-9a9aa648-cea4-4e2c-ae7e-43d1ec16be04.png)
