### ISSUE TITLE
Antique Atlas Transparency Bug when used with Oculus Shader

### ISSUE THREAD

**Issue by NilsZe** [Hunternif/AntiqueAtlas#448]
I'm using Antique Atlas Version 7.0.3 on Minecraft 1.18.2 and Forge 40.1.84.
As soon as shaders are activated the handheld antique atlas is getting some unwanted transparencies. 
I experienced the problem with different shaders while using Rubidium and Oculus. 
Turning several options on/off on the video settings/shaderpack options didn't help.
![2022-10-17_14 14 39](https://user-images.githubusercontent.com/115996535/196175260-3f60a7da-c652-409b-91be-b603e7a11a28.png)

**Comment by tyra314** [comment]
Mostly the same issue like #416

**Comment by tyra314** [comment]
which shader are you using? BSL and Sildurs Vibrant work fine for me.

**Comment by NilsZe** [comment]
> 

I also got the problem with BSL
![Screenshot 2022-10-18 231218](https://user-images.githubusercontent.com/115996535/196546059-4b339dd7-e947-4395-a028-901e4e57e67f.png)
