### ISSUE TITLE
cannot clone atlas in latest 1.16.5 forge version

### ISSUE THREAD

**Issue by Bruhinatorr** [Hunternif/AntiqueAtlas#449]
**Describe the bug**
cloning atlas doesnt work

**To Reproduce**
1. Use The latest 1.16.5 version
2. Try to combine an atlas with an empty atlas in crafting table
3. Nothing Happens

**Expected behavior**
2 copies of atlas should be the result of the crafting

**Screenshots**
![image](https://user-images.githubusercontent.com/115116574/197198047-c0acaa37-8baf-4c38-a3e1-544c3889fb75.png)

**Version information (please complete the following information):**
 - AntiqueAtlas: 6.2.2 & 6.2.1
 - Minecraft: 1.16.5
 - Forge: 36.2.34
 
**Additional context**
version 6.0.1 works as indented didnt test 6.2.0

**Comment by tyra314** [comment]
Dang, it also happens on Fabric.

**Comment by tyra314** [comment]
Fixed in 6.2.3

And commit 6aa1010ae6b9ff3dfff6d95483c847377857ce8d
