### ISSUE TITLE
Whenever I have the mod enabled on forge it crashes with the error code 1 saying that a mixin reply failed

### ISSUE THREAD

**Issue by ToasterOvenDev** [Hunternif/AntiqueAtlas#454]
**Describe the bug**
I open the game and enable the output log to see the problem and it comes up that there is a mixin reply failing 

**To Reproduce**
No idea

**Expected behavior**
The game opening.

**Version information (please complete the following information):**
 - AntiqueAtlas: 6.1.0
 - Minecraft: 1.17.1
 - Forge: 37.1.1

**Comment by tyra314** [comment]
Please provide the crash log.

**Comment by ToasterOvenDev** [comment]
I was able to resolve the issue it was a conflict with another mod.
