### ISSUE TITLE
Biome O plenty's nether biomes have missing textures.

### ISSUE THREAD

**Issue by OverEarth12** [Hunternif/AntiqueAtlas#456]
**Describe the bug**
From issue: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/433
1.16.5 still have this issue in nether.

**To Reproduce**
1.Install Biome O Plenty and Antique Atlas.
2.Create new world and go to nether
3.Open the atlas and find some BOP biomes.

**Expected behavior**
Normal texture like other biomes in nether

**Screenshots**
![2023-01-24_10 37 05](https://user-images.githubusercontent.com/56574543/214210912-e8066c69-e36f-4dd6-a81c-30fdef566928.png)

**Version information (please complete the following information):**
 - AntiqueAtlas: antiqueatlas-6.2.3-forge-mc1.16.5
 - Minecraft: 1.16.5
 - Forge: 36.2.34

**Comment by tyra314** [comment]
Fixed in the upcoming version 6.2.4.

Still, were will only be generic textures. For the best experience, you'd need a resource pack supporting BoP.
