### ISSUE TITLE
1.18.2 quilt client random crash on startup

### ISSUE THREAD

**Issue by ghost** [Hunternif/AntiqueAtlas#458]
[crash-2023-03-15_13.20.36-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/10976263/crash-2023-03-15_13.20.36-client.txt)
[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/10976267/latest.log)
not sure whether it's mod's fault or quilt's.
the normal startup log: 
[2023-03-15-1.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/10976288/2023-03-15-1.log)

**Comment by tyra314** [comment]
This is the same issue as #438, which is already fixed. However, I just realized I never did a release since the fix was introduced. Guess I'll do a release soon:tm:
