### ISSUE TITLE
Modded biomes look broken

### ISSUE THREAD

**Issue by DarkScorn** [Hunternif/AntiqueAtlas#460]
**Describe the bug**
Terralith biomes look broken in antique atlas.

**To Reproduce**
1. Download and create a world with Terralith (v. 2.2.3)
2. Use antique atlas in that world
3. See how Terralith biomes look in atlas.

**Expected behavior**
Biomes not looking like in the first screenshot but more like the second screenshot.

**Screenshots**
![2023-03-18_20 33 52](https://user-images.githubusercontent.com/24631889/226124427-f61e433c-0ded-43ce-9b52-434debc33d15.png)

and with antique atlas 7.0.3,
![2023-03-18_20 53 35](https://user-images.githubusercontent.com/24631889/226124611-08d19efd-3f2d-4bb3-af79-9ea3e1f477d0.png)

**Version information (please complete the following information):**
 - AntiqueAtlas: 7.1.0 1.18.2
 - Minecraft: 1.18.2
 - Forge: 40.2.0

**Comment by tyra314** [comment]
Yeah, I also got that on [discord](https://discord.com/channels/265589396588199937/265589396588199937/1086247124469035049), and it happens for all kinds of modded biomes.
