### ISSUE TITLE
Cannt enable minimap mode for atlas

### ISSUE THREAD

**Issue by Skiexx** [Hunternif/AntiqueAtlas#469]
**Describe the bug**
Cannt enable minimap mode for atlas

**To Reproduce**
1. Download mode
2. Check .toml file

**Expected behavior**
Find field for configure minimap mode

**Screenshots**
Expect see minimap like that
![image](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/assets/95953737/1c2118ca-3a2c-4563-b1bc-a3bad9318072)
But see like that
![image](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/assets/95953737/3373c365-fd63-4f5f-8f9f-7b0888b57f1b)
Or not see at all
![image](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/assets/95953737/25f0e892-051d-46d3-b1b9-930a27b8daab)

**Version information (please complete the following information):**
 - AntiqueAtlas: 7.1.1
 - Minecraft: 1.18.2
 - Forge: 40.2.10
 
**Additional context**
Please add all config fields for enabling atlas minimap or add settings field

**Comment by tyra314** [comment]
The minimap is gone and won't come back (as part of the mod itself. If somebody else would like to make a third-party addon, feel free to do that). The atlas should behave like the vanilla map; when you have the map selected and look down, it should be shown like in the second image. If you have it in your off-hand, it should be some sort of minimap in the off-hand corner.

The only issue here I'm seeing is that the map isn't rendered in the third image at all.

**Comment by Skiexx** [comment]
> The minimap is gone and won't come back (as part of the mod itself. If somebody else would like to make a third-party addon, feel free to do that). The atlas should behave like the vanilla map; when you have the map selected and look down, it should be shown like in the second image. If you have it in your off-hand, it should be some sort of minimap in the off-hand corner.
> 
> The only issue here I'm seeing is that the map isn't rendered in the third image at all.

On last screen I use modpack downcraft. It has mod for better perspective. Like in rpg.

**Comment by tyra314** [comment]
Then there's no bug here. It's working as intended.
