### ISSUE TITLE
1.19.2 support?

### ISSUE THREAD

**Issue by RemagOfficial** [Hunternif/AntiqueAtlas#473]
is there any chance that there will be an update to 1.19.2 forge or is 1.19.X being skipped completely?

**Comment by TheOverpassArsonist** [comment]
A pull request already exists for 19.2 that **_appears_** to be mostly complete, #467 to be exact.

Not a developer on the project, haven't worked on any of the commits, and frankly don't even have any modding experience, but from my brief glimpses at the PR it looks, at least superficially, decently far along.

Also it's generally best to check around first for PRs, projects, branches, discussions, etc. for different versions before opening a new issue for version ports. If there aren't any and there isn't any information on ports in an FAQ, wiki, etc. then making an issue can be the right approach (if only to ask for some clarification on the porting process, what versions will/might be supported, etc.) but in general it clutters the repo unnecessarily. For small projects that's not necessarily an issue, but the larger a mod gets the more it can cause information fragmentation and general clutter. Admittedly a lot of mods **_don't_** have those,even though I really think they should, but it's good practice to check just in case. (A lot of the time mods just rely entirely on discord servers to communicate that sort of information which is very sub-optimal for countless reasons.)

**Comment by RemagOfficial** [comment]
I have checked PRs and that one only has releases for fabric so I assumed that the forge code wasn't updated

**Comment by tyra314** [comment]
Not an issue.
