### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by Aabaddon** [Hunternif/AntiqueAtlas#478]
i saw an "antique atlas reborn" but it exist no more... i really need this mod for 1.20.1 but it seems kile you dont want to upgrade from 1.18 for some reason

**Comment by BioTechproject27** [comment]
Agree, a port to 1.20+ versions would be pretty cool! This is an amazing mod

**Comment by squimbo** [comment]
I am begging for this

**Comment by tyra314** [comment]
Not an issue.

**Comment by BioTechproject27** [comment]
> Not an issue.

Nope, a suggestion

But is there any particularly reason you don't want to?
