### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Arch23-tech** [Hunternif/AntiqueAtlas#486]
Plz for the love of God ... update this mod to 1.20.1 l, everyone is begging... others forks of this mod already exists for 1.20.1 but none of them works.....

**Comment by sanches2114** [comment]
I agree

> пожалуйста из любви к Богу... Обновите этот мод до 1.20.1 л, все умоляют... Другие форки этого мода уже существуют для 1.20.1, но ни один из них не работает.....

**Comment by tyra314** [comment]
Not an issue in the sense of GitHub issues.
