### ISSUE TITLE
screen gets dark whenever i pull up the map on antique Atlas 4

### ISSUE THREAD

**Issue by mrbluegame** [Hunternif/AntiqueAtlas#487]
whenever i open the map my entire screen quickly gets dark im using neoforge 1.21

**Comment by tyra314** [comment]
Wrong repo. This is antique atlas, not antique atlas 4

**Comment by mrbluegame** [comment]
> Wrong repo. This is antique atlas, not antique atlas 4

mb

**Comment by mrbluegame** [comment]
> Wrong repo. This is antique atlas, not antique atlas 4

where is the Antique Atlas 4 support page? i cannot find it
