### ISSUE TITLE
Minimap mode

### ISSUE THREAD

**Issue by Hunternif** [Hunternif/AntiqueAtlas#49]

**Comment by Kenkron** [comment]
Hi, I'm kenkron. I'm working on this as an addon over [here](https://github.com/Kenkron/AntiqueAtlasOverlay).

**Comment by Hunternif** [comment]
Hey Kenkon, that's awesome!

**Comment by Kenkron** [comment]
Minimap has been fully merged with this mod as of b58197eb82a629c6227426b24955fc0fa29f1076. This applies to versions for 1.9.4 moving forward, and has moved the version number up to 4.3.  Previous requirements for 4.3 have been pushed back to 4.4, so that I don't have to keep updating two mods.
