### ISSUE TITLE
1.8 crash when cloning or combining atlases.

### ISSUE THREAD

**Issue by Hunternif** [Hunternif/AntiqueAtlas#51]
Possibly due to NEI.
See crash log: https://gist.github.com/jpastuszek/1c6d9b5bff5a8ef55f8f

**Comment by jpastuszek** [comment]
Hi, I did'n notice this mod is on GitHub :)

I have tried cloning without NEI and CodeChicken on Single Player (creative gamemode 0) - same effect.
https://gist.github.com/jpastuszek/7b924a4ce05a4fca61c9
