### ISSUE TITLE
Did i do anything wrong? :O!!! 

### ISSUE THREAD

**Issue by Beanius** [Hunternif/AntiqueAtlas#56]
http://pastebin.com/4HvhsSzR
Got this after i downloaded the latest version? :3

**Comment by Hunternif** [comment]
I'm sorry! Something went wrong in during the build process, and the release file was not obfuscated correctly. I replaced the file with the correct one, please re-download it.

**Comment by Beanius** [comment]
Aye thanks alot !! ^^, keep up with the awesome work!!! Antique Atlas is my favorite map mod :D
