### ISSUE TITLE
Minimum and maximum zoom levels

### ISSUE THREAD

**Issue by PureSpider** [Hunternif/AntiqueAtlas#62]
Have a setting in the settings file that allows you to set min/max zoom levels for the map, optionally per dimension.

**Comment by Hunternif** [comment]
I can rather easily add a setting for min/max zoom level in general for all maps and all dimensions. Are you sure more fine-tuning is needed?

**Comment by PureSpider** [comment]
All maps and all dimensions equally as a global setting was what I was thinking about! Finer control is not needed from my side 😊

**Comment by PureSpider** [comment]
Perfect! Thank you! :+1:
