### ISSUE TITLE
Server side required - or just a regular'ol crash

### ISSUE THREAD

**Issue by DanTheColoradan** [Hunternif/AntiqueAtlas#65]
I installed the curse version 4.2.7-18 and when I attempt to create an atlas, the game bombs.

[crash-2015-12-07_11.01.05.txt](https://github.com/Hunternif/AntiqueAtlas/files/54383/crash-2015-12-07_11.01.05.txt)

I also couldn't determine if the server needs to have the mod installed as well. Perhaps that is the problem? I might help others to add that to the mod description.

Thanks!

**Comment by Hunternif** [comment]
Yes, both server and client side is required for now. I'll try to make it more clear from the description.
I assume this doesn't happen if you install it on the server as well?

**Comment by DanTheColoradan** [comment]
I'll give it a try this weekend! Thanks.

**Comment by DanTheColoradan** [comment]
Works!

It does seem odd that it would allow me to connect and attempt to create an atlas even though the server didn't have the mod. But no reason to keep this open :)

Thanks :beers:

**Comment by Hunternif** [comment]
That's interesting. Did you have Forge installed on the server?

**Comment by DanTheColoradan** [comment]
Yeah. I can try to recreate it if you'd like?

**Comment by Hunternif** [comment]
No, thanks, I'll have to look into it later anyway.

**Comment by Hunternif** [comment]
No need actually, I think I understand why it worked the way it did. It should get fixed when I finally get to making the client-only version of the mod.

**Comment by DanTheColoradan** [comment]
Nice! Ok :)
