### ISSUE TITLE
Is AntiqueAtlas only supposed to work with MC 1.8.0?

### ISSUE THREAD

**Issue by charlesbevans** [Hunternif/AntiqueAtlas#76]
I tried adding AntiqueAtlas to FTB Unstable (MC 1.8.9) and got a message that it was for a different version. Is this intended, simple to correct, or was the 1.8.0-1.8.9 series of updates a modding nightmare?

**Comment by Kenkron** [comment]
1.8 and 1.8.9 are actually incompatible.  1.8.9 will be up soon.

**Comment by Hunternif** [comment]
Any mod is generally only guaranteed to work with the MC version it was built for. Different MC versions may or may not be compatible.
